"""
STANDALONE, config-CSV-driven architecture search comparing TWO hypernetwork training
strategies across many random main-net (f) architectures. Separate from train_loo.py and
every train_loo_basediff*/train_loo_deltaweights* script -- only READS (imports, unmodified)
data_loader.py, model.py's HyperNetwork/main_net_forward/main_net_n_params/ACTIVATION_FNS,
and train_loo.py's build_tensors/train_hypernet/evaluate (the "original" strategy is just
train_loo.py's own pipeline, reused as-is).

Two strategies scored, same f-architecture set, same gm1_weight:
  "original" -- train_loo.py's pipeline: H(Vgsq,Vdsq) -> theta -> f(Vgs,Vds;theta). Standard
                6-fold LOO (train on 5, hold out 1).
  "delta"    -- train_loo_deltaweights_reg.py's pipeline, reimplemented here WITH gm1 support
                added (the original script didn't have it): theta_base fit once on BASE_KEY's
                own data (frozen), H_comp(Vgsq,Vdsq) -> delta_theta, theta_total = theta_base +
                delta_theta, Ids_pred = main_net_forward(theta_total, ...). BASE_KEY always in
                the training set (its own delta_theta target is ~0 by construction), so LOO
                runs over the other 5 quiescent points, 5 training points per fold.

Config files (generated by the `generate` subcommand):
  f_architectures.csv -- one row per candidate f architecture: arch_hash, architecture (JSON
                         per-neuron activation lists), n_layers, n_neurons_total, n_params,
                         tanh_only (bool). Uses tanh/swish/linear; --n_tanh_only rows are
                         forced all-tanh (default 150 of 1000).
  h_architectures.csv -- one row per H size to test: h_arch_hash, h_hidden, h_layers. Default:
                         the project's current best (32,1) plus 3/4, 1/2, 1/4 of the hidden
                         width at the same depth (24,1) (16,1) (8,1).

The `run` subcommand cross-joins f_architectures.csv x h_architectures.csv x {original,delta},
trains each combo as a fast-proxy fold-parallel sweep (fewer epochs, no L-BFGS -- same
"ranking proxy, not confirmed result" convention as architecture_search.py), and APPENDS one
row per combo to results.csv (safe to re-run/extend: existing arch_hash+h_arch_hash+strategy
rows are skipped). Each combo's full-fit model (trained on ALL quiescent points, not a LOO
fold) is saved under --models_dir/<combo_id>/ along with a meta.json with everything needed
to reconstruct it (architecture, h_hidden, h_layers, n_params, strategy, gm1_weight,
delta_reg_weight, base_key) -- results.csv's model_dir column points to that directory as a
path RELATIVE TO results.csv's own location (not absolute), so the whole output tree
(results.csv + models_dir) stays valid if copied/moved to a new location or machine, as long
as the two are moved together and keep their relative position to each other.

Usage:
  # 1. generate the two config files (1000 f-architectures, 4 H sizes)
  python architecture_search_delta.py generate --n_f_architectures 1000 --n_tanh_only 150

  # 2. smoke test: only the first 5 rows of f_architectures.csv x 4 H sizes x 2 strategies = 40 combos
  python architecture_search_delta.py run --n_f_architectures 5 --workers 12 --gm1_weight 0.075

  # 3. (NOT run automatically) the full sweep: all 1000 f-architectures
  python architecture_search_delta.py run --workers 15 --gm1_weight 0.075
"""
import argparse
import csv
import hashlib
import json
import os
import time
from concurrent.futures import ProcessPoolExecutor, as_completed

import numpy as np
import torch
import torch.nn as nn

from data_loader import load_all
from model import HyperNetwork, main_net_forward, main_net_n_params
from train_loo import build_tensors as build_tensors_full, train_hypernet, evaluate as evaluate_original

VGS_SCALE = 4.0
VDS_SCALE = 45.0
BASE_KEY = (-2.9, 0.0)  # only used by the "delta" strategy -- same reference as
                        # train_loo_basediff.py / train_loo_deltaweights_*.py
ACTIVATIONS_FOR_SEARCH = ("tanh", "swish", "linear")

F_ARCH_CSV_FIELDS = ["arch_hash", "architecture", "n_layers", "n_neurons_total", "n_params", "tanh_only"]
H_ARCH_CSV_FIELDS = ["h_arch_hash", "h_hidden", "h_layers"]
RESULTS_CSV_FIELDS = [
    "combo_id", "f_arch_hash", "h_arch_hash", "strategy", "gm1_weight", "delta_reg_weight",
    "epochs", "lbfgs_epochs", "n_params_f", "h_hidden", "h_layers",
    "loo_mean_rel_rmse", "loo_n_points", "loo_worst_rel_rmse", "full_fit_mean_rel_rmse",
    "loo_per_point_json", "model_dir", "status", "error_msg", "wall_time_seconds", "timestamp",
]


# ============================== hashing & generation ==============================

def arch_hash_of(obj):
    s = json.dumps(obj, sort_keys=True)
    return hashlib.sha1(s.encode()).hexdigest()[:12]


def random_f_architecture(rng, min_layers, max_layers, min_neurons, max_neurons, tanh_only):
    n_layers = int(rng.integers(min_layers, max_layers + 1))
    acts = ("tanh",) if tanh_only else ACTIVATIONS_FOR_SEARCH
    arch = []
    for _ in range(n_layers):
        n_neurons = int(rng.integers(min_neurons, max_neurons + 1))
        layer = [acts[i] for i in rng.integers(0, len(acts), size=n_neurons)]
        arch.append(layer)
    return arch


def generate_f_architectures(n, n_tanh_only, seed, min_layers=1, max_layers=3, min_neurons=6, max_neurons=16):
    rng = np.random.default_rng(seed)
    rows, seen = [], set()

    def try_add(tanh_only):
        arch = random_f_architecture(rng, min_layers, max_layers, min_neurons, max_neurons, tanh_only)
        h = arch_hash_of(arch)
        if h in seen:
            return False
        seen.add(h)
        rows.append(dict(
            arch_hash=h, architecture=json.dumps(arch), n_layers=len(arch),
            n_neurons_total=sum(len(layer) for layer in arch), n_params=main_net_n_params(arch),
            tanh_only=all(a == "tanh" for layer in arch for a in layer),
        ))
        return True

    n_forced_tanh = 0
    while n_forced_tanh < n_tanh_only:
        if try_add(tanh_only=True):
            n_forced_tanh += 1
    while len(rows) < n:
        try_add(tanh_only=False)
    return rows


def generate_h_architectures(base_hidden=32, base_layers=1):
    variants = [1.0, 0.75, 0.5, 0.25]
    rows = []
    for frac in variants:
        hidden = max(1, round(base_hidden * frac))
        row = dict(h_hidden=hidden, h_layers=base_layers)
        row["h_arch_hash"] = arch_hash_of(row)
        rows.append(row)
    return rows


def write_csv(path, rows, fields):
    dirname = os.path.dirname(path)
    if dirname:
        os.makedirs(dirname, exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def read_csv(path):
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def cmd_generate(args):
    f_rows = generate_f_architectures(args.n_f_architectures, args.n_tanh_only, args.seed,
                                       args.min_layers, args.max_layers, args.min_neurons, args.max_neurons)
    write_csv(args.f_csv, f_rows, F_ARCH_CSV_FIELDS)
    n_tanh_actual = sum(1 for r in f_rows if r["tanh_only"])
    print(f"Wrote {len(f_rows)} f-architectures to {args.f_csv} ({n_tanh_actual} tanh-only)")

    h_rows = generate_h_architectures(args.h_base_hidden, args.h_base_layers)
    write_csv(args.h_csv, h_rows, H_ARCH_CSV_FIELDS)
    print(f"Wrote {len(h_rows)} H-architectures to {args.h_csv}:")
    for r in h_rows:
        print(f"  {r}")


# ============================== "delta" strategy training (with gm1) ==============================

def rel_rmse(pred, true):
    return float(np.sqrt(np.mean((pred - true) ** 2)) / (np.abs(true).max() + 1e-30))


def fit_theta_base(df, n_params, architecture, epochs, lr, lbfgs_epochs, lbfgs_max_iter, seed):
    """Same idea as train_loo_deltaweights_reg.py's fit_theta_base -- reimplemented here
    (not imported) since this module owns its own self-contained training code."""
    torch.manual_seed(seed)
    vgs = torch.tensor(df["Vgs"].values / VGS_SCALE, dtype=torch.float32)
    vds = torch.tensor(df["Vds"].values / VDS_SCALE, dtype=torch.float32)
    ids = torch.tensor(df["Ids"].values, dtype=torch.float32)
    norm = (ids.abs().max().item() + 1e-6) ** 2

    theta = nn.Parameter(torch.randn(n_params) * 0.3)
    opt = torch.optim.Adam([theta], lr=lr)
    for _ in range(epochs):
        opt.zero_grad()
        pred = main_net_forward(theta, vgs, vds, architecture)
        loss = torch.mean((pred - ids) ** 2) / norm
        loss.backward()
        opt.step()

    if lbfgs_epochs > 0:
        lbfgs = torch.optim.LBFGS([theta], max_iter=lbfgs_max_iter, line_search_fn="strong_wolfe")

        def closure():
            lbfgs.zero_grad()
            pred = main_net_forward(theta, vgs, vds, architecture)
            loss = torch.mean((pred - ids) ** 2) / norm
            loss.backward()
            return loss

        for _ in range(lbfgs_epochs):
            lbfgs.step(closure)

    with torch.no_grad():
        pred = main_net_forward(theta, vgs, vds, architecture).numpy()
    return theta.detach(), rel_rmse(pred, ids.numpy())


def _delta_total_loss(hcomp, theta_base, train_keys, tensors, architecture, norm,
                       gm1_weight, gm1_norm, delta_reg_weight):
    """Same structure as train_loo.py's _total_loss (gm1 term identical), applied to
    theta_total = theta_base + delta_theta instead of a hypernetwork-only theta."""
    total = 0.0
    for k in train_keys:
        t = tensors[k]
        delta = hcomp(t["qpoint"])
        theta_total = theta_base + delta
        pred = main_net_forward(theta_total, t["vgs"], t["vds"], architecture)
        loss = torch.mean((pred - t["ids"]) ** 2) / norm[k]

        if gm1_weight > 0:
            gm_vgs_req = t["gm_vgs"].clone().requires_grad_(True)
            ids_gm = main_net_forward(theta_total, gm_vgs_req / VGS_SCALE, t["gm_vds"], architecture)
            gm1_pred = torch.autograd.grad(ids_gm, gm_vgs_req, grad_outputs=torch.ones_like(ids_gm),
                                            create_graph=True)[0]
            loss_gm1 = torch.mean((gm1_pred - t["gm1_true"]) ** 2) / gm1_norm[k]
            loss = loss + gm1_weight * loss_gm1

        if delta_reg_weight > 0:
            loss = loss + delta_reg_weight * torch.mean(delta ** 2)

        total = total + loss
    return total


def train_hcomp(train_keys, tensors, theta_base, n_params, architecture, epochs, lr, device,
                 gm1_weight, delta_reg_weight, lbfgs_epochs, lbfgs_max_iter, h_hidden, h_layers, seed):
    torch.manual_seed(seed)
    hcomp = HyperNetwork(n_params, hidden=h_hidden, n_hidden_layers=h_layers, n_in=2).to(device)
    opt = torch.optim.Adam(hcomp.parameters(), lr=lr)

    norm = {k: (np.abs(tensors[k]["ids_np"]).max() + 1e-6) ** 2 for k in train_keys}
    gm1_norm = {}
    if gm1_weight > 0:
        gm1_norm = {k: (tensors[k]["gm1_true"].abs().max().item() + 1e-6) ** 2 for k in train_keys}

    for _ in range(epochs):
        opt.zero_grad()
        loss = _delta_total_loss(hcomp, theta_base, train_keys, tensors, architecture, norm,
                                  gm1_weight, gm1_norm, delta_reg_weight)
        loss.backward()
        opt.step()

    if lbfgs_epochs > 0:
        lbfgs_opt = torch.optim.LBFGS(hcomp.parameters(), max_iter=lbfgs_max_iter, line_search_fn="strong_wolfe")

        def closure():
            lbfgs_opt.zero_grad()
            loss = _delta_total_loss(hcomp, theta_base, train_keys, tensors, architecture, norm,
                                      gm1_weight, gm1_norm, delta_reg_weight)
            loss.backward()
            return loss

        for _ in range(lbfgs_epochs):
            lbfgs_opt.step(closure)

    return hcomp


def evaluate_delta(hcomp, theta_base, key, tensors, architecture):
    t = tensors[key]
    with torch.no_grad():
        delta = hcomp(t["qpoint"])
        theta_total = theta_base + delta
        pred = main_net_forward(theta_total, t["vgs"], t["vds"], architecture).cpu().numpy()
    return rel_rmse(pred, t["ids_np"]), pred


# ============================== fold-level jobs (max parallelism grain) ==============================

def run_fold_original(f_arch_hash, h_arch_hash, architecture, n_params, h_hidden, h_layers,
                       held_out, data, epochs, lr, gm1_weight, lbfgs_epochs, seed):
    torch.set_num_threads(1)
    device = torch.device("cpu")
    keys = sorted(data.keys())
    train_keys = [k for k in keys if k != held_out]
    tensors = build_tensors_full(data, device)
    hyper = train_hypernet(train_keys, tensors, n_params, architecture, epochs, lr, device,
                            gm1_weight=gm1_weight, lbfgs_epochs=lbfgs_epochs,
                            h_hidden=h_hidden, h_layers=h_layers, n_in=2, log_every=0, seed=seed)
    err, _ = evaluate_original(hyper, held_out, tensors, architecture, device)
    return f_arch_hash, h_arch_hash, "original", held_out, err


def run_fold_delta(f_arch_hash, h_arch_hash, architecture, n_params, h_hidden, h_layers,
                    held_out, data, theta_base, epochs, lr, gm1_weight, delta_reg_weight,
                    lbfgs_epochs, seed):
    torch.set_num_threads(1)
    device = torch.device("cpu")
    all_keys = sorted(data.keys())
    other_keys = [k for k in all_keys if k != BASE_KEY]
    train_keys = [BASE_KEY] + [k for k in other_keys if k != held_out]
    tensors = build_tensors_full(data, device)
    hcomp = train_hcomp(train_keys, tensors, theta_base, n_params, architecture, epochs, lr, device,
                         gm1_weight=gm1_weight, delta_reg_weight=delta_reg_weight,
                         lbfgs_epochs=lbfgs_epochs, lbfgs_max_iter=200,
                         h_hidden=h_hidden, h_layers=h_layers, seed=seed)
    err, _ = evaluate_delta(hcomp, theta_base, held_out, tensors, architecture)
    return f_arch_hash, h_arch_hash, "delta", held_out, err


def run_full_fit_original(f_arch_hash, h_arch_hash, architecture, n_params, h_hidden, h_layers,
                           data, epochs, lr, gm1_weight, lbfgs_epochs, seed, save_dir):
    torch.set_num_threads(1)
    device = torch.device("cpu")
    keys = sorted(data.keys())
    tensors = build_tensors_full(data, device)
    hyper = train_hypernet(keys, tensors, n_params, architecture, epochs, lr, device,
                            gm1_weight=gm1_weight, lbfgs_epochs=lbfgs_epochs,
                            h_hidden=h_hidden, h_layers=h_layers, n_in=2, log_every=0, seed=seed)
    errs = {}
    for k in keys:
        err, _ = evaluate_original(hyper, k, tensors, architecture, device)
        errs[k] = err
    os.makedirs(save_dir, exist_ok=True)
    torch.save(hyper.state_dict(), os.path.join(save_dir, "hyper_full.pt"))
    meta = dict(strategy="original", architecture=architecture, h_hidden=h_hidden, h_layers=h_layers,
                n_params=n_params, gm1_weight=gm1_weight)
    with open(os.path.join(save_dir, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)
    return f_arch_hash, h_arch_hash, "original", float(np.mean(list(errs.values())))


def run_full_fit_delta(f_arch_hash, h_arch_hash, architecture, n_params, h_hidden, h_layers,
                        data, theta_base, epochs, lr, gm1_weight, delta_reg_weight, lbfgs_epochs,
                        seed, save_dir):
    torch.set_num_threads(1)
    device = torch.device("cpu")
    keys = sorted(data.keys())
    tensors = build_tensors_full(data, device)
    hcomp = train_hcomp(keys, tensors, theta_base, n_params, architecture, epochs, lr, device,
                         gm1_weight=gm1_weight, delta_reg_weight=delta_reg_weight,
                         lbfgs_epochs=lbfgs_epochs, lbfgs_max_iter=200,
                         h_hidden=h_hidden, h_layers=h_layers, seed=seed)
    errs = {}
    for k in keys:
        err, _ = evaluate_delta(hcomp, theta_base, k, tensors, architecture)
        errs[k] = err
    os.makedirs(save_dir, exist_ok=True)
    torch.save(hcomp.state_dict(), os.path.join(save_dir, "hcomp_full.pt"))
    torch.save(theta_base, os.path.join(save_dir, "theta_base.pt"))
    meta = dict(strategy="delta", architecture=architecture, h_hidden=h_hidden, h_layers=h_layers,
                n_params=n_params, gm1_weight=gm1_weight, delta_reg_weight=delta_reg_weight,
                base_key=list(BASE_KEY))
    with open(os.path.join(save_dir, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)
    return f_arch_hash, h_arch_hash, "delta", float(np.mean(list(errs.values())))


def fit_theta_base_job(f_arch_hash, architecture, n_params, data, base_epochs, base_lr,
                        lbfgs_epochs, lbfgs_max_iter, seed):
    """Runs in its own process -- one per f-architecture (shared across all 4 H sizes)."""
    torch.set_num_threads(1)
    theta_base, base_err = fit_theta_base(data[BASE_KEY], n_params, architecture, base_epochs,
                                           base_lr, lbfgs_epochs, lbfgs_max_iter, seed)
    return f_arch_hash, theta_base, base_err


# ============================== run orchestration ==============================

def cmd_run(args):
    f_rows = read_csv(args.f_csv)
    if args.n_f_architectures is not None:
        f_rows = f_rows[:args.n_f_architectures]
    h_rows = read_csv(args.h_csv)
    print(f"Loaded {len(f_rows)} f-architectures from {args.f_csv}, "
          f"{len(h_rows)} H-architectures from {args.h_csv}")

    existing = set()
    if os.path.exists(args.results_csv):
        for r in read_csv(args.results_csv):
            existing.add((r["f_arch_hash"], r["h_arch_hash"], r["strategy"]))
        print(f"{len(existing)} combos already in {args.results_csv} -- will be skipped")

    data = load_all(args.csv_dir)
    keys = sorted(data.keys())
    other_keys = [k for k in keys if k != BASE_KEY]
    print("Quiescent points found:", keys, " BASE_KEY:", BASE_KEY)

    combos = []  # (f_row, h_row, strategy)
    for f_row in f_rows:
        for h_row in h_rows:
            for strategy in ("original", "delta"):
                if (f_row["arch_hash"], h_row["h_arch_hash"], strategy) in existing:
                    continue
                combos.append((f_row, h_row, strategy))
    print(f"{len(combos)} new combos to run "
          f"({len(f_rows)} f-archs x {len(h_rows)} H-archs x 2 strategies, minus already-done)")
    if not combos:
        print("Nothing to do.")
        return

    # --- Step 1: fit theta_base once per DISTINCT f-architecture that needs the "delta" strategy ---
    f_archs_needing_base = {}
    for f_row, h_row, strategy in combos:
        if strategy == "delta":
            f_archs_needing_base[f_row["arch_hash"]] = f_row
    theta_base_by_farch = {}
    base_err_by_farch = {}
    if f_archs_needing_base:
        print(f"\nFitting theta_base for {len(f_archs_needing_base)} distinct f-architectures "
              f"({args.base_epochs} epochs + {args.base_lbfgs_epochs} L-BFGS)...")
        with ProcessPoolExecutor(max_workers=args.workers) as ex:
            futs = {
                ex.submit(fit_theta_base_job, arch_hash, json.loads(f_row["architecture"]),
                          int(f_row["n_params"]), data, args.base_epochs, args.base_lr,
                          args.base_lbfgs_epochs, args.lbfgs_max_iter, args.seed): arch_hash
                for arch_hash, f_row in f_archs_needing_base.items()
            }
            for fut in as_completed(futs):
                arch_hash, theta_base, base_err = fut.result()
                theta_base_by_farch[arch_hash] = theta_base
                base_err_by_farch[arch_hash] = base_err
        print(f"  done ({len(theta_base_by_farch)} theta_base vectors fit).")

    # --- Step 2: submit fold-level jobs (max parallelism) for LOO scoring ---
    t0 = time.time()
    fold_futures = {}
    with ProcessPoolExecutor(max_workers=args.workers) as ex:
        for f_row, h_row, strategy in combos:
            architecture = json.loads(f_row["architecture"])
            n_params = int(f_row["n_params"])
            h_hidden, h_layers = int(h_row["h_hidden"]), int(h_row["h_layers"])
            if strategy == "original":
                for held_out in keys:
                    fut = ex.submit(run_fold_original, f_row["arch_hash"], h_row["h_arch_hash"],
                                     architecture, n_params, h_hidden, h_layers, held_out, data,
                                     args.epochs, args.lr, args.gm1_weight, args.lbfgs_epochs, args.seed)
                    fold_futures[fut] = (f_row["arch_hash"], h_row["h_arch_hash"], strategy)
            else:
                theta_base = theta_base_by_farch[f_row["arch_hash"]]
                for held_out in other_keys:
                    fut = ex.submit(run_fold_delta, f_row["arch_hash"], h_row["h_arch_hash"],
                                     architecture, n_params, h_hidden, h_layers, held_out, data,
                                     theta_base, args.epochs, args.lr, args.gm1_weight,
                                     args.delta_reg_weight, args.lbfgs_epochs, args.seed)
                    fold_futures[fut] = (f_row["arch_hash"], h_row["h_arch_hash"], strategy)

        print(f"\nSubmitted {len(fold_futures)} LOO-fold jobs across {args.workers} workers "
              f"({args.epochs} epochs each, fast proxy) ...")
        per_combo_errs = {}
        done = 0
        for fut in as_completed(fold_futures):
            f_arch_hash, h_arch_hash, strategy, held_out, err = fut.result()
            per_combo_errs.setdefault((f_arch_hash, h_arch_hash, strategy), {})[held_out] = err
            done += 1
            if done % 100 == 0 or done == len(fold_futures):
                print(f"  {done}/{len(fold_futures)} folds done ({time.time()-t0:.0f}s elapsed)")

    # --- Step 3: full-fit job per combo (for the saved/reconstructable model) ---
    print(f"\nRunning {len(combos)} full-fit jobs (saved models) ...")
    fullfit_by_combo = {}
    with ProcessPoolExecutor(max_workers=args.workers) as ex:
        futs = {}
        for f_row, h_row, strategy in combos:
            architecture = json.loads(f_row["architecture"])
            n_params = int(f_row["n_params"])
            h_hidden, h_layers = int(h_row["h_hidden"]), int(h_row["h_layers"])
            combo_id = f"{f_row['arch_hash']}_{h_row['h_arch_hash']}_{strategy}"
            save_dir = os.path.join(args.models_dir, combo_id)
            if strategy == "original":
                fut = ex.submit(run_full_fit_original, f_row["arch_hash"], h_row["h_arch_hash"],
                                 architecture, n_params, h_hidden, h_layers, data, args.epochs,
                                 args.lr, args.gm1_weight, args.lbfgs_epochs, args.seed, save_dir)
            else:
                theta_base = theta_base_by_farch[f_row["arch_hash"]]
                fut = ex.submit(run_full_fit_delta, f_row["arch_hash"], h_row["h_arch_hash"],
                                 architecture, n_params, h_hidden, h_layers, data, theta_base,
                                 args.epochs, args.lr, args.gm1_weight, args.delta_reg_weight,
                                 args.lbfgs_epochs, args.seed, save_dir)
            futs[fut] = (f_row, h_row, strategy, combo_id, save_dir)
        for fut in as_completed(futs):
            f_row, h_row, strategy, combo_id, save_dir = futs[fut]
            try:
                _, _, _, full_fit_mean = fut.result()
                fullfit_by_combo[combo_id] = (full_fit_mean, save_dir, None)
            except Exception as e:
                fullfit_by_combo[combo_id] = (float("nan"), save_dir, str(e))

    # --- Step 4: assemble + append results.csv ---
    # model_dir is stored RELATIVE to results.csv's own directory (not absolute) so the whole
    # output tree (results.csv + models_dir) stays valid if copied/moved elsewhere together --
    # an absolute path here would silently go stale on any copy-paste to a new location/machine.
    results_csv_dir = os.path.dirname(os.path.abspath(args.results_csv))
    write_header = not os.path.exists(args.results_csv)
    with open(args.results_csv, "a", newline="") as f:
        w = csv.DictWriter(f, fieldnames=RESULTS_CSV_FIELDS)
        if write_header:
            w.writeheader()
        for f_row, h_row, strategy in combos:
            combo_id = f"{f_row['arch_hash']}_{h_row['h_arch_hash']}_{strategy}"
            key = (f_row["arch_hash"], h_row["h_arch_hash"], strategy)
            errs_by_point = per_combo_errs.get(key, {})
            n_expected = len(keys) if strategy == "original" else len(other_keys)
            status = "ok" if len(errs_by_point) == n_expected else "incomplete"
            errs = list(errs_by_point.values())
            full_fit_mean, save_dir, err_msg = fullfit_by_combo.get(combo_id, (float("nan"), "", "missing"))
            model_dir_rel = os.path.relpath(save_dir, results_csv_dir) if save_dir else ""
            w.writerow(dict(
                combo_id=combo_id,
                f_arch_hash=f_row["arch_hash"],
                h_arch_hash=h_row["h_arch_hash"],
                strategy=strategy,
                gm1_weight=args.gm1_weight,
                delta_reg_weight=args.delta_reg_weight if strategy == "delta" else "",
                epochs=args.epochs,
                lbfgs_epochs=args.lbfgs_epochs,
                n_params_f=f_row["n_params"],
                h_hidden=h_row["h_hidden"],
                h_layers=h_row["h_layers"],
                loo_mean_rel_rmse=float(np.mean(errs)) if errs else "",
                loo_n_points=len(errs),
                loo_worst_rel_rmse=float(np.max(errs)) if errs else "",
                full_fit_mean_rel_rmse=full_fit_mean,
                loo_per_point_json=json.dumps({qtag_local(*k): v for k, v in errs_by_point.items()}),
                model_dir=model_dir_rel,
                status=status if err_msg is None else "error",
                error_msg=err_msg or "",
                wall_time_seconds=round(time.time() - t0, 1),
                timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
            ))

    print(f"\nAppended {len(combos)} rows to {args.results_csv}")
    print(f"Saved models under {args.models_dir}/<combo_id>/")


def qtag_local(vgsq, vdsq):
    return f"Vgsq{vgsq:g}_Vdsq{vdsq:g}"


# ============================== CLI ==============================

def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    g = sub.add_parser("generate", help="Write f_architectures.csv and h_architectures.csv")
    g.add_argument("--f_csv", default="configs/arch_search_1000/f_architectures.csv")
    g.add_argument("--h_csv", default="configs/arch_search_1000/h_architectures.csv")
    g.add_argument("--n_f_architectures", type=int, default=1000)
    g.add_argument("--n_tanh_only", type=int, default=150)
    g.add_argument("--min_layers", type=int, default=1)
    g.add_argument("--max_layers", type=int, default=3)
    g.add_argument("--min_neurons", type=int, default=6)
    g.add_argument("--max_neurons", type=int, default=16)
    g.add_argument("--h_base_hidden", type=int, default=32)
    g.add_argument("--h_base_layers", type=int, default=1)
    g.add_argument("--seed", type=int, default=42)
    g.set_defaults(func=cmd_generate)

    r = sub.add_parser("run", help="Run the sweep, appending to results.csv")
    r.add_argument("--csv_dir", default=r"C:\Users\acost\repos\csvs")
    r.add_argument("--f_csv", default="configs/arch_search_1000/f_architectures.csv")
    r.add_argument("--h_csv", default="configs/arch_search_1000/h_architectures.csv")
    r.add_argument("--results_csv",
                    default=r"C:\Users\acost\repos\transistor_modeling_hyper_outputs\results.csv",
                    help="Appended to incrementally; safe to re-run/extend. Defaults OUTSIDE "
                         "this repo (sibling folder) so runs never create untracked files "
                         "inside the git repo -- pass an absolute path to write anywhere else.")
    r.add_argument("--models_dir",
                    default=r"C:\Users\acost\repos\transistor_modeling_hyper_outputs\archsearch_models",
                    help="Saved model weights + meta.json per combo. Defaults OUTSIDE this repo "
                         "(sibling folder), same reasoning as --results_csv.")
    r.add_argument("--n_f_architectures", type=int, default=None,
                    help="Limit to the first N rows of f_csv (e.g. 5 for a smoke test). "
                         "Default: use all rows in f_csv.")
    r.add_argument("--workers", type=int, required=True)
    r.add_argument("--epochs", type=int, default=1000,
                    help="Fast-proxy epoch count for LOO-fold ranking (no L-BFGS by default).")
    r.add_argument("--lr", type=float, default=3e-3)
    r.add_argument("--lbfgs_epochs", type=int, default=0)
    r.add_argument("--lbfgs_max_iter", type=int, default=200)
    r.add_argument("--gm1_weight", type=float, default=0.075)
    r.add_argument("--delta_reg_weight", type=float, default=0.01)
    r.add_argument("--base_epochs", type=int, default=2000)
    r.add_argument("--base_lr", type=float, default=3e-3)
    r.add_argument("--base_lbfgs_epochs", type=int, default=5)
    r.add_argument("--seed", type=int, default=27)
    r.set_defaults(func=cmd_run)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
