"""
STANDALONE, config-CSV-driven architecture search comparing TWO hypernetwork training
strategies across many random main-net (f) architectures. Separate from train_loo.py and
every train_loo_basediff*/train_loo_deltaweights* script -- only READS (imports, unmodified)
data_loader.py, model.py's HyperNetwork/main_net_forward/main_net_n_params/ACTIVATION_FNS,
and train_loo.py's build_tensors/train_hypernet/evaluate (the "original" strategy is just
train_loo.py's own pipeline, reused as-is).

Two strategies TRAINED, same f-architecture set, same gm1_weight, plus a third DERIVED one:
  "original" -- train_loo.py's pipeline: H(Vgsq,Vdsq) -> theta -> f(Vgs,Vds;theta). Standard
                6-fold LOO (train on 5, hold out 1).
  "delta"    -- train_loo_deltaweights_reg.py's pipeline, reimplemented here WITH gm1 support
                added (the original script didn't have it): theta_base fit once on BASE_KEY's
                own data (frozen), H_comp(Vgsq,Vdsq) -> delta_theta, theta_total = theta_base +
                delta_theta, Ids_pred = main_net_forward(theta_total, ...). BASE_KEY always in
                the training set (its own delta_theta target is ~0 by construction), so LOO
                runs over the other 5 quiescent points, 5 training points per fold.
  "ensemble" -- NOT trained: whenever both "original" and "delta" are (re)trained for the same
                (f_arch_hash, h_arch_hash) pair in the same `run` batch, their predictions are
                simply averaged at every point both cover, scored the same way, and recorded
                as a third pseudo-combo (see scratch_ensemble_original_delta.py for the
                one-off manual analysis this generalizes -- there, averaging helped when the
                two strategies were reasonably competitive, hurt when one was much worse).
                Has no saved weights of its own; its metrics.json's source_original_combo_id/
                source_delta_combo_id name the two real combos it was averaged from.

Config files (generated by the `generate` subcommand):
  f_architectures.csv -- one row per candidate f architecture: arch_hash, architecture (JSON
                         per-neuron activation lists), n_layers, n_neurons_total, n_params,
                         tanh_only (bool). Uses tanh/swish/linear; --n_tanh_only rows are
                         forced all-tanh (default 150 of 1000).
  h_architectures.csv -- one row per H size to test: h_arch_hash, h_hidden, h_layers. Default:
                         the project's current best (32,1) plus 3/4, 1/2, 1/4 of the hidden
                         width at the same depth (24,1) (16,1) (8,1).

Training and result-aggregation are deliberately TWO SEPARATE steps/subcommands, not one:

  `run` -- cross-joins f_architectures.csv x h_architectures.csv x {original,delta} and trains
           each combo as a fast-proxy fold-parallel sweep (fewer epochs, no L-BFGS -- same
           "ranking proxy, not confirmed result" convention as architecture_search.py). ONLY
           writes files under --models_dir/<combo_id>/ -- it never touches results.csv at all:
             meta.json    -- everything needed to reconstruct the model (architecture, h_hidden,
                             h_layers, n_params, strategy, gm1_weight, delta_reg_weight, base_key)
             hyper_full.pt (original) or hcomp_full.pt + theta_base.pt (delta) -- the trained weights
             metrics.json -- the LOO/full-fit scores for this combo (everything a results.csv
                             row needs); its EXISTENCE is what marks the combo "done"
           Resume logic scans the FILESYSTEM, not any CSV: a combo is skipped if
           --models_dir/<combo_id>/metrics.json already exists, so pausing (Ctrl+C at any
           point) and re-running the exact same command later picks up cleanly -- no results.csv
           needs to exist or be consulted at all. Combos are processed in --batch_size chunks
           purely for ProcessPoolExecutor parallelism grain; each combo's own metrics.json is
           written as soon as ITS training finishes, not batched/buffered.
           No paths are stored inside meta.json/metrics.json -- a combo's own directory name
           (<f_arch_hash>_<h_arch_hash>_<strategy>) is self-describing, so moving/copying
           --models_dir anywhere (a different folder, a different machine) never invalidates
           anything inside it.

  `populate` -- separately, and as many times as you like, WITHOUT retraining anything: scans
           every --models_dir/<combo_id>/metrics.json it can find and (re)builds results.csv
           from scratch (one row per combo with a metrics.json). Safe to run mid-sweep (partial
           results so far), after moving --models_dir to a new machine, or repeatedly as more
           combos finish -- it is a fast, read-only aggregation pass, no PyTorch/training
           involved. model_dir in the output CSV is just each combo's directory name (relative
           to --models_dir), so the CSV stays correct regardless of where --models_dir lives.
           With --with_gm it ALSO reloads each combo's full-fit model to score gm1/gm2/gm3
           (and combined_gm) rel-RMSE into the same CSV, cached per combo in
           <combo_id>/gm_metrics.json -- that opt-in pass does load PyTorch + the CSVs.

Usage:
  # 1. generate the two config files (1000 f-architectures, 4 H sizes)
  python architecture_search_strategies.py generate --n_f_architectures 1000 --n_tanh_only 150

  # 2. smoke test: only the first 5 rows of f_architectures.csv x 4 H sizes x 2 strategies = 40 combos
  python architecture_search_strategies.py run --n_f_architectures 5 --workers 12 --gm1_weight 0.075

  # 3. (NOT run automatically) the full sweep: all 1000 f-architectures
  python architecture_search_strategies.py run --workers 15 --gm1_weight 0.075

  # 4. any time (before, during, or after the sweep finishes) -- (re)build results.csv
  python architecture_search_strategies.py populate
"""
import argparse
import csv
import hashlib
import itertools
import json
import os
import time
from concurrent.futures import ProcessPoolExecutor, as_completed

import numpy as np
import torch
import torch.nn as nn

from data_loader import load_all
from model import HyperNetwork, main_net_forward, main_net_n_params
from signal_utils import smooth_derivative, gm_vds_target_list, GM_VDS_STEP, GM_SMOOTHING_METHODS
from train_loo import build_tensors as build_tensors_full, train_hypernet, evaluate as evaluate_original


def _worker_warmup():
    """ProcessPoolExecutor(initializer=...) hook: constructing the FIRST torch.optim.AdamW in a
    freshly-spawned process lazily imports torch._dynamo -> networkx, which reads every
    installed package's entry_points.txt via importlib.metadata. With --workers this high,
    many worker processes hit that at once right after pool startup, and on Windows this has
    been observed to throw a transient OSError([Errno 22] Invalid argument) reading one of
    those files -- not a bug in this script, a race in the OS/filesystem layer. Since it's a
    ONE-TIME cost per process (later AdamW constructions in the same worker don't re-trigger
    the import), do it once here at pool startup, with retries, so a real training job never
    eats this race."""
    import time
    for attempt in range(6):
        try:
            torch.optim.AdamW([torch.zeros(1, requires_grad=True)], lr=1e-3)
            return
        except OSError:
            if attempt == 5:
                raise
            time.sleep(0.5 * (attempt + 1))


VGS_SCALE = 4.0
VDS_SCALE = 45.0
BASE_KEY = (-2.9, 0.0)  # only used by the "delta" strategy -- same reference as
                        # train_loo_basediff.py / train_loo_deltaweights_*.py
ACTIVATIONS_FOR_SEARCH = ("tanh", "swish", "linear")
# Fixed per-LAYER composition for "mixed" (non-tanh_only) architectures: each layer's neurons
# are split tanh/swish/linear as close to these percentages as its neuron count allows (exact
# counts, not random per-neuron draws -- see layer_composition). Which neuron position gets
# which activation is irrelevant (order doesn't affect the network), only the resulting counts
# do, so positions are just filled tanh-block, then swish-block, then linear-block.
DEFAULT_ACTIVATION_WEIGHTS = (0.6, 0.3, 0.1)  # (tanh, swish, linear), must sum to 1.0

F_ARCH_CSV_FIELDS = ["arch_hash", "architecture", "n_layers", "n_neurons_total", "n_params", "tanh_only"]
H_ARCH_CSV_FIELDS = ["h_arch_hash", "h_hidden", "h_layers"]
RESULTS_CSV_FIELDS = [
    "combo_id", "f_arch_hash", "h_arch_hash", "strategy", "hp_hash",
    "source_original_combo_id", "source_delta_combo_id",  # only populated for strategy="ensemble"
    "gm1_weight", "gm_smoothing", "delta_reg_weight", "weight_decay", "epochs", "lr", "lbfgs_epochs",
    "lbfgs_max_iter", "delta_base_epochs", "delta_base_lr", "delta_base_lbfgs_epochs", "seed",
    "n_params_f", "h_hidden", "h_layers",
    "loo_mean_rel_rmse", "loo_n_points", "loo_worst_rel_rmse", "full_fit_mean_rel_rmse",
    # gm1/gm2/gm3 = 1st/2nd/3rd d/dVgs of Ids; combined_gm = equal-weight mean of the three.
    # gm*_rel_rmse: full-fit model, filled by `populate --with_gm` (blank otherwise).
    # loo_gm*_rel_rmse: held-out folds -- native in metrics.json when `run` produced this combo,
    # else filled by `populate --with_loo_gm` (top-N retrain). See run_gm_metrics_pass / run_loo_gm_pass.
    "gm1_rel_rmse", "gm2_rel_rmse", "gm3_rel_rmse", "combined_gm_rel_rmse",
    "loo_gm1_rel_rmse", "loo_gm2_rel_rmse", "loo_gm3_rel_rmse", "loo_combined_gm_rel_rmse",
    "loo_per_point_json", "model_dir", "status", "error_msg", "wall_time_seconds", "timestamp",
]


# ============================== hashing & generation ==============================

def arch_hash_of(obj):
    s = json.dumps(obj, sort_keys=True)
    return hashlib.sha1(s.encode()).hexdigest()[:12]


def layer_composition(n_neurons, weights):
    """Splits n_neurons into (n_tanh, n_swish, n_linear) counts as close to `weights` (a
    (tanh,swish,linear) fraction triple) as integer counts allow. Uses floor() for each
    target then hands out the few leftover neurons one at a time, tanh first then swish then
    linear, which keeps tanh/swish counts >= their floor share (matters most for small layers,
    e.g. a 6-neuron layer at (0.6,0.3,0.1) floors to (3,1,0) with 2 left over -> (4,2,0))."""
    tanh_w, swish_w, linear_w = weights
    n_tanh = int(n_neurons * tanh_w)
    n_swish = int(n_neurons * swish_w)
    n_linear = int(n_neurons * linear_w)
    remainder = n_neurons - (n_tanh + n_swish + n_linear)
    counts = [n_tanh, n_swish, n_linear]
    for i in range(remainder):
        counts[i % 3] += 1
    return tuple(counts)


FALLBACK_ACTIVATION_WEIGHTS = (0.6, 0.2, 0.2)  # (tanh, swish, linear) -- used only once the
# primary weights (DEFAULT_ACTIVATION_WEIGHTS) exhaust the distinct-size-tuple space below
# 1000 unique architectures; a different weight triple gives the SAME size-tuples a different
# (still deterministic) composition, so re-visiting them under fallback weights yields new,
# still-unique architectures instead of duplicates.


def enumerate_size_tuples(min_layers, max_layers, min_neurons, max_neurons,
                           min_neurons_total=None, max_neurons_total=None):
    """Every distinct (n1, n2, ..., n_k) neuron-count-per-layer combination, k from min_layers
    to max_layers, order-sensitive (layer 1's size differs positionally from layer 2's -- a
    network is sequential, so (6,10) and (10,6) are genuinely different architectures).
    Returned GROUPED by depth ({n_layers: [tuple, ...]}), not flattened -- the possible-tuple
    count grows combinatorially with depth (11 for 1 layer, 121 for 2, 1331 for 3 at the
    default 6-16 neuron range), so a flat pooled shuffle statistically drowns the shallow
    depths out; callers should sample depth-stratified (see round_robin_size_tuples).

    min_neurons/max_neurons bound EACH layer; the optional min_neurons_total/max_neurons_total
    bound sum(tuple) (the whole main-net's neuron count). Depths left with no surviving tuple
    are dropped from the returned dict."""
    lo = min_neurons_total if min_neurons_total is not None else 0
    hi = max_neurons_total if max_neurons_total is not None else float("inf")
    sizes = list(range(min_neurons, max_neurons + 1))
    out = {}
    for n_layers in range(min_layers, max_layers + 1):
        tuples = [t for t in itertools.product(sizes, repeat=n_layers) if lo <= sum(t) <= hi]
        if tuples:
            out[n_layers] = tuples
    return out


def round_robin_size_tuples(by_depth, rng):
    """Yields size-tuples round-robin across depths (each depth's own pool shuffled
    independently first), so the much smaller shallow-depth pools (11 one-layer, 121
    two-layer vs. 1331 three-layer at the default range) are fully exhausted before the
    combinatorially larger deep pool dominates purely by volume -- guarantees every possible
    1- and 2-layer architecture gets tried instead of them being statistically drowned out."""
    pools = {depth: list(tuples) for depth, tuples in by_depth.items()}
    for pool in pools.values():
        rng.shuffle(pool)
    depths = sorted(pools.keys())
    idxs = {d: 0 for d in depths}
    while True:
        progressed = False
        for d in depths:
            if idxs[d] < len(pools[d]):
                yield pools[d][idxs[d]]
                idxs[d] += 1
                progressed = True
        if not progressed:
            return


def build_arch(sizes, tanh_only, activation_weights=None):
    """sizes: tuple of neuron-counts, one per layer. Composition per layer is a DETERMINISTIC
    function of (n_neurons, activation_weights) -- see layer_composition -- neuron order within
    a layer is fixed (tanh-block, swish-block, linear-block) since order carries no meaning."""
    if tanh_only:
        return [["tanh"] * n for n in sizes]
    arch = []
    for n in sizes:
        n_tanh, n_swish, n_linear = layer_composition(n, activation_weights)
        arch.append(["tanh"] * n_tanh + ["swish"] * n_swish + ["linear"] * n_linear)
    return arch


def enumerate_f_architectures(min_layers, max_layers, min_neurons, max_neurons,
                               min_neurons_total, max_neurons_total,
                               weight_variants=(DEFAULT_ACTIVATION_WEIGHTS, FALLBACK_ACTIVATION_WEIGHTS)):
    """FULL enumeration (no sampling, no `n`): every surviving size-tuple emitted as 100% tanh
    plus one arch per triple in weight_variants, collapsed by arch_hash. Small layers whose
    composition is identical across variants (e.g. a 3-neuron layer is (2,1,0) under both
    (0.6,0.3,0.1) and (0.6,0.2,0.2)) therefore contribute only their distinct architectures --
    so you get "<=3 per size-tuple", not exactly 3. Deterministic, order = shallow depths then
    lexicographic size-tuple."""
    by_depth = enumerate_size_tuples(min_layers, max_layers, min_neurons, max_neurons,
                                      min_neurons_total, max_neurons_total)
    rows, seen = [], set()

    def add(arch):
        h = arch_hash_of(arch)
        if h in seen:
            return
        seen.add(h)
        rows.append(dict(
            arch_hash=h, architecture=json.dumps(arch), n_layers=len(arch),
            n_neurons_total=sum(len(layer) for layer in arch), n_params=main_net_n_params(arch),
            tanh_only=all(a == "tanh" for layer in arch for a in layer),
        ))

    for depth in sorted(by_depth):
        for sizes in sorted(by_depth[depth]):
            add(build_arch(sizes, tanh_only=True))
            for w in weight_variants:
                add(build_arch(sizes, tanh_only=False, activation_weights=w))
    return rows


def generate_f_architectures(n, n_tanh_only, seed, min_layers=1, max_layers=3, min_neurons=6,
                              max_neurons=16, primary_weights=DEFAULT_ACTIVATION_WEIGHTS,
                              fallback_weights=FALLBACK_ACTIVATION_WEIGHTS,
                              min_neurons_total=None, max_neurons_total=None):
    """Builds n architectures (n_tanh_only of them 100% tanh, the rest mixed) via depth-
    stratified round-robin over every distinct layer-size combination (see
    enumerate_size_tuples/round_robin_size_tuples) -- NOT independent random sampling with
    reject-on-duplicate (which wastes draws, isn't guaranteed to terminate, AND would still
    let the combinatorially larger deep-network pool statistically dominate). The tanh_only
    bucket and the mixed bucket each get their OWN independent round-robin pass over the full
    by-depth pools (freshly shuffled), so BOTH buckets separately get full depth coverage --
    reusing the same underlying size-tuples across buckets is fine and intentional (a
    tanh_only architecture and a mixed one built from the same sizes are never the same
    architecture, since their actual per-layer composition differs). If primary_weights can't
    reach n mixed architectures even after exhausting every depth's pool, a second
    (independently shuffled) round-robin pass is run under fallback_weights -- a different
    weight triple gives the SAME sizes a different, still-deterministic composition, so this
    yields genuinely new architectures rather than duplicates."""
    rng = np.random.default_rng(seed)
    by_depth = enumerate_size_tuples(min_layers, max_layers, min_neurons, max_neurons,
                                      min_neurons_total, max_neurons_total)

    rows, seen = [], set()

    def add_row(arch):
        h = arch_hash_of(arch)
        if h in seen:
            return False
        seen.add(h)
        rows.append(dict(
            arch_hash=h, architecture=json.dumps(arch), n_layers=len(arch),
            n_neurons_total=sum(len(layer) for layer in arch), n_params=main_net_n_params(arch),
            tanh_only=all(a == "tanh" for layer in arch for a in layer),
        ))
        return True

    # 1. n_tanh_only architectures (100% tanh), own depth-stratified pass
    n_forced_tanh = 0
    for sizes in round_robin_size_tuples(by_depth, rng):
        if n_forced_tanh >= n_tanh_only:
            break
        if add_row(build_arch(sizes, tanh_only=True)):
            n_forced_tanh += 1
    if n_forced_tanh < n_tanh_only:
        raise RuntimeError(f"Only {n_forced_tanh}/{n_tanh_only} tanh-only architectures were "
                            f"reachable -- widen --min_neurons/--max_neurons/--max_layers.")

    # 2. mixed architectures: primary weights first (own depth-stratified pass), falling back
    # to a second depth-stratified pass under fallback_weights if that alone isn't enough
    n_mixed_needed = n - n_tanh_only
    n_mixed_added = 0
    for sizes in round_robin_size_tuples(by_depth, rng):
        if n_mixed_added >= n_mixed_needed:
            break
        if add_row(build_arch(sizes, tanh_only=False, activation_weights=primary_weights)):
            n_mixed_added += 1
    if n_mixed_added < n_mixed_needed:
        print(f"  primary weights {primary_weights} exhausted the size-tuple space at "
              f"{len(rows)}/{n} architectures -- switching to fallback weights "
              f"{fallback_weights} for the remaining {n_mixed_needed - n_mixed_added}")
        for sizes in round_robin_size_tuples(by_depth, rng):
            if n_mixed_added >= n_mixed_needed:
                break
            if add_row(build_arch(sizes, tanh_only=False, activation_weights=fallback_weights)):
                n_mixed_added += 1
    if n_mixed_added < n_mixed_needed:
        raise RuntimeError(f"Only reached {len(rows)}/{n} architectures even after falling back "
                            f"to {fallback_weights} -- widen the size ranges or lower --n_f_architectures.")
    return rows


def generate_h_architectures(base_hidden=32, base_layers=1):
    variants = [1.0, 0.75, 0.5, 0.25]
    rows = []
    for frac in variants:
        hidden = max(1, round(base_hidden * frac))
        row = dict(h_hidden=hidden, h_layers=base_layers)
        row["h_arch_hash"] = arch_hash_of(row)
        rows.append(row)
    return rows


def write_csv(path, rows, fields):
    dirname = os.path.dirname(path)
    if dirname:
        os.makedirs(dirname, exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def read_csv(path):
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def cmd_generate(args):
    if args.enumerate_all:
        f_rows = enumerate_f_architectures(args.min_layers, args.max_layers, args.min_neurons,
                                            args.max_neurons, args.min_neurons_total,
                                            args.max_neurons_total)
        if not f_rows:
            raise SystemExit("no size-tuples satisfy the given per-layer / total constraints")
    else:
        f_rows = generate_f_architectures(args.n_f_architectures, args.n_tanh_only, args.seed,
                                           args.min_layers, args.max_layers, args.min_neurons,
                                           args.max_neurons, min_neurons_total=args.min_neurons_total,
                                           max_neurons_total=args.max_neurons_total)
    write_csv(args.f_csv, f_rows, F_ARCH_CSV_FIELDS)
    n_tanh_actual = sum(1 for r in f_rows if r["tanh_only"])
    tot = [r["n_neurons_total"] for r in f_rows]
    print(f"Wrote {len(f_rows)} f-architectures to {args.f_csv} ({n_tanh_actual} tanh-only, "
          f"{len(f_rows) - n_tanh_actual} mixed; total-neuron range {min(tot)}-{max(tot)})")

    h_rows = generate_h_architectures(args.h_base_hidden, args.h_base_layers)
    write_csv(args.h_csv, h_rows, H_ARCH_CSV_FIELDS)
    print(f"Wrote {len(h_rows)} H-architectures to {args.h_csv}:")
    for r in h_rows:
        print(f"  {r}")


# ============================== "delta" strategy training (with gm1) ==============================

def rel_rmse(pred, true):
    return float(np.sqrt(np.mean((pred - true) ** 2)) / (np.abs(true).max() + 1e-30))


def fit_theta_base(df, n_params, architecture, epochs, lr, lbfgs_epochs, lbfgs_max_iter, seed,
                    weight_decay=0.0):
    """Same idea as train_loo_deltaweights_reg.py's fit_theta_base -- reimplemented here
    (not imported) since this module owns its own self-contained training code."""
    torch.manual_seed(seed)
    vgs = torch.tensor(df["Vgs"].values / VGS_SCALE, dtype=torch.float32)
    vds = torch.tensor(df["Vds"].values / VDS_SCALE, dtype=torch.float32)
    ids = torch.tensor(df["Ids"].values, dtype=torch.float32)
    norm = (ids.abs().max().item() + 1e-6) ** 2

    theta = nn.Parameter(torch.randn(n_params) * 0.3)
    opt = torch.optim.AdamW([theta], lr=lr, weight_decay=weight_decay)
    for _ in range(epochs):
        opt.zero_grad()
        pred = main_net_forward(theta, vgs, vds, architecture)
        loss = torch.mean((pred - ids) ** 2) / norm
        loss.backward()
        opt.step()

    if lbfgs_epochs > 0:
        lbfgs = torch.optim.LBFGS([theta], max_iter=lbfgs_max_iter, line_search_fn="strong_wolfe")

        def closure():
            lbfgs.zero_grad()
            pred = main_net_forward(theta, vgs, vds, architecture)
            loss = torch.mean((pred - ids) ** 2) / norm
            loss.backward()
            return loss

        for _ in range(lbfgs_epochs):
            lbfgs.step(closure)

    with torch.no_grad():
        pred = main_net_forward(theta, vgs, vds, architecture).numpy()
    return theta.detach(), rel_rmse(pred, ids.numpy())


def _delta_total_loss(hcomp, theta_base, train_keys, tensors, architecture, norm,
                       gm1_weight, gm1_norm, delta_reg_weight):
    """Same structure as train_loo.py's _total_loss (gm1 term identical), applied to
    theta_total = theta_base + delta_theta instead of a hypernetwork-only theta."""
    total = 0.0
    for k in train_keys:
        t = tensors[k]
        delta = hcomp(t["qpoint"])
        theta_total = theta_base + delta
        pred = main_net_forward(theta_total, t["vgs"], t["vds"], architecture)
        loss = torch.mean((pred - t["ids"]) ** 2) / norm[k]

        if gm1_weight > 0:
            gm_vgs_req = t["gm_vgs"].clone().requires_grad_(True)
            ids_gm = main_net_forward(theta_total, gm_vgs_req / VGS_SCALE, t["gm_vds"], architecture)
            gm1_pred = torch.autograd.grad(ids_gm, gm_vgs_req, grad_outputs=torch.ones_like(ids_gm),
                                            create_graph=True)[0]
            loss_gm1 = torch.mean((gm1_pred - t["gm1_true"]) ** 2) / gm1_norm[k]
            loss = loss + gm1_weight * loss_gm1

        if delta_reg_weight > 0:
            loss = loss + delta_reg_weight * torch.mean(delta ** 2)

        total = total + loss
    return total


def train_hcomp(train_keys, tensors, theta_base, n_params, architecture, epochs, lr, device,
                 gm1_weight, delta_reg_weight, lbfgs_epochs, lbfgs_max_iter, h_hidden, h_layers, seed,
                 weight_decay=0.0):
    torch.manual_seed(seed)
    hcomp = HyperNetwork(n_params, hidden=h_hidden, n_hidden_layers=h_layers, n_in=2).to(device)
    # AdamW (weight_decay=0.0 default is a no-op, identical to plain Adam) -- see train_loo.py's
    # train_hypernet for the same reasoning: regularizes H_comp's weights directly, aimed at
    # the generalization gap, not "escaping local minima".
    opt = torch.optim.AdamW(hcomp.parameters(), lr=lr, weight_decay=weight_decay)

    norm = {k: (np.abs(tensors[k]["ids_np"]).max() + 1e-6) ** 2 for k in train_keys}
    gm1_norm = {}
    if gm1_weight > 0:
        gm1_norm = {k: (tensors[k]["gm1_true"].abs().max().item() + 1e-6) ** 2 for k in train_keys}

    for _ in range(epochs):
        opt.zero_grad()
        loss = _delta_total_loss(hcomp, theta_base, train_keys, tensors, architecture, norm,
                                  gm1_weight, gm1_norm, delta_reg_weight)
        loss.backward()
        opt.step()

    if lbfgs_epochs > 0:
        lbfgs_opt = torch.optim.LBFGS(hcomp.parameters(), max_iter=lbfgs_max_iter, line_search_fn="strong_wolfe")

        def closure():
            lbfgs_opt.zero_grad()
            loss = _delta_total_loss(hcomp, theta_base, train_keys, tensors, architecture, norm,
                                      gm1_weight, gm1_norm, delta_reg_weight)
            loss.backward()
            return loss

        for _ in range(lbfgs_epochs):
            lbfgs_opt.step(closure)

    return hcomp


def evaluate_delta(hcomp, theta_base, key, tensors, architecture):
    t = tensors[key]
    with torch.no_grad():
        delta = hcomp(t["qpoint"])
        theta_total = theta_base + delta
        pred = main_net_forward(theta_total, t["vgs"], t["vds"], architecture).cpu().numpy()
    return rel_rmse(pred, t["ids_np"]), pred


# ============================== fold-level jobs (max parallelism grain) ==============================

def _fold_gm_safe(data, held_out, net, architecture, theta_base=None):
    """gm1/gm2/gm3 (+combined) rel-RMSE on the HELD-OUT point for a just-trained fold model,
    computed while the model is still in memory (Option C -- see the gm-metrics section).
    Returns the 4-field dict or None; never raises (a gm hiccup must not fail a training fold)."""
    try:
        predict = _predict_ids_fn(net, architecture, held_out[0], held_out[1], theta_base)
        return _gm_rel_rmses_one_qpoint(data[held_out], predict, GM_VDS_STEP)
    except Exception:
        return None


def run_fold_original(f_arch_hash, h_arch_hash, architecture, n_params, h_hidden, h_layers,
                       held_out, data, epochs, lr, gm1_weight, lbfgs_epochs, seed, weight_decay,
                       gm_smoothing="savgol"):
    torch.set_num_threads(1)
    device = torch.device("cpu")
    keys = sorted(data.keys())
    train_keys = [k for k in keys if k != held_out]
    tensors = build_tensors_full(data, device, gm_smoothing=gm_smoothing)
    hyper, _ = train_hypernet(train_keys, tensors, n_params, architecture, epochs, lr, device,
                               gm1_weight=gm1_weight, lbfgs_epochs=lbfgs_epochs,
                               h_hidden=h_hidden, h_layers=h_layers, n_in=2, log_every=0, seed=seed,
                               weight_decay=weight_decay)
    err, pred = evaluate_original(hyper, held_out, tensors, architecture, device)
    gm = _fold_gm_safe(data, held_out, hyper, architecture)
    return f_arch_hash, h_arch_hash, "original", held_out, err, pred, gm


def run_fold_delta(f_arch_hash, h_arch_hash, architecture, n_params, h_hidden, h_layers,
                    held_out, data, theta_base, epochs, lr, gm1_weight, delta_reg_weight,
                    lbfgs_epochs, seed, weight_decay, gm_smoothing="savgol"):
    torch.set_num_threads(1)
    device = torch.device("cpu")
    all_keys = sorted(data.keys())
    other_keys = [k for k in all_keys if k != BASE_KEY]
    train_keys = [BASE_KEY] + [k for k in other_keys if k != held_out]
    tensors = build_tensors_full(data, device, gm_smoothing=gm_smoothing)
    hcomp = train_hcomp(train_keys, tensors, theta_base, n_params, architecture, epochs, lr, device,
                         gm1_weight=gm1_weight, delta_reg_weight=delta_reg_weight,
                         lbfgs_epochs=lbfgs_epochs, lbfgs_max_iter=200,
                         h_hidden=h_hidden, h_layers=h_layers, seed=seed, weight_decay=weight_decay)
    err, pred = evaluate_delta(hcomp, theta_base, held_out, tensors, architecture)
    gm = _fold_gm_safe(data, held_out, hcomp, architecture, theta_base)
    return f_arch_hash, h_arch_hash, "delta", held_out, err, pred, gm


def run_full_fit_original(f_arch_hash, h_arch_hash, architecture, n_params, h_hidden, h_layers,
                           data, epochs, lr, gm1_weight, lbfgs_epochs, seed, weight_decay, save_dir,
                           gm_smoothing="savgol"):
    torch.set_num_threads(1)
    device = torch.device("cpu")
    keys = sorted(data.keys())
    tensors = build_tensors_full(data, device, gm_smoothing=gm_smoothing)
    hyper, _ = train_hypernet(keys, tensors, n_params, architecture, epochs, lr, device,
                               gm1_weight=gm1_weight, lbfgs_epochs=lbfgs_epochs,
                               h_hidden=h_hidden, h_layers=h_layers, n_in=2, log_every=0, seed=seed,
                               weight_decay=weight_decay)
    errs, preds = {}, {}
    for k in keys:
        err, pred = evaluate_original(hyper, k, tensors, architecture, device)
        errs[k] = err
        preds[k] = pred
    os.makedirs(save_dir, exist_ok=True)
    torch.save(hyper.state_dict(), os.path.join(save_dir, "hyper_full.pt"))
    meta = dict(strategy="original", architecture=architecture, h_hidden=h_hidden, h_layers=h_layers,
                n_params=n_params, gm1_weight=gm1_weight, weight_decay=weight_decay,
                gm_smoothing=gm_smoothing)
    with open(os.path.join(save_dir, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)
    return f_arch_hash, h_arch_hash, "original", float(np.mean(list(errs.values()))), preds


def run_full_fit_delta(f_arch_hash, h_arch_hash, architecture, n_params, h_hidden, h_layers,
                        data, theta_base, epochs, lr, gm1_weight, delta_reg_weight, lbfgs_epochs,
                        seed, weight_decay, save_dir, gm_smoothing="savgol"):
    torch.set_num_threads(1)
    device = torch.device("cpu")
    keys = sorted(data.keys())
    tensors = build_tensors_full(data, device, gm_smoothing=gm_smoothing)
    hcomp = train_hcomp(keys, tensors, theta_base, n_params, architecture, epochs, lr, device,
                         gm1_weight=gm1_weight, delta_reg_weight=delta_reg_weight,
                         lbfgs_epochs=lbfgs_epochs, lbfgs_max_iter=200,
                         h_hidden=h_hidden, h_layers=h_layers, seed=seed, weight_decay=weight_decay)
    errs, preds = {}, {}
    for k in keys:
        err, pred = evaluate_delta(hcomp, theta_base, k, tensors, architecture)
        errs[k] = err
        preds[k] = pred
    os.makedirs(save_dir, exist_ok=True)
    torch.save(hcomp.state_dict(), os.path.join(save_dir, "hcomp_full.pt"))
    torch.save(theta_base, os.path.join(save_dir, "theta_base.pt"))
    meta = dict(strategy="delta", architecture=architecture, h_hidden=h_hidden, h_layers=h_layers,
                n_params=n_params, gm1_weight=gm1_weight, delta_reg_weight=delta_reg_weight,
                weight_decay=weight_decay, base_key=list(BASE_KEY), gm_smoothing=gm_smoothing)
    with open(os.path.join(save_dir, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)
    return f_arch_hash, h_arch_hash, "delta", float(np.mean(list(errs.values()))), preds


def fit_theta_base_job(f_arch_hash, architecture, n_params, data, delta_base_epochs, delta_base_lr,
                        lbfgs_epochs, lbfgs_max_iter, seed, weight_decay):
    """Runs in its own process -- one per f-architecture (shared across all 4 H sizes)."""
    torch.set_num_threads(1)
    theta_base, base_err = fit_theta_base(data[BASE_KEY], n_params, architecture, delta_base_epochs,
                                           delta_base_lr, lbfgs_epochs, lbfgs_max_iter, seed,
                                           weight_decay=weight_decay)
    return f_arch_hash, theta_base, base_err


# ============================== run orchestration ==============================

# Every hyperparameter that can change what a combo's TRAINING actually produces (not
# execution mechanics like --workers/--batch_size, which don't affect the trained result).
# Generic on purpose: hyperparams_hash_of just hashes whatever args attributes are named
# here, so adding a new training hyperparameter to `run` later only requires adding its name
# to this list, not touching the hashing logic itself.
HYPERPARAM_ARGS = ["epochs", "lr", "lbfgs_epochs", "lbfgs_max_iter", "gm1_weight",
                   "delta_reg_weight", "weight_decay", "delta_base_epochs", "delta_base_lr",
                   "delta_base_lbfgs_epochs", "seed", "gm_smoothing"]

# HYPERPARAM_ARGS entries left OUT of the hash when they hold this value -- so adding a new
# training knob whose default reproduces the old behaviour does NOT rehash (and thus orphan)
# every combo trained before the knob existed. gm_smoothing="savgol" is exactly what
# build_gm_targets did unconditionally before commit 1760ca2.
HYPERPARAM_HASH_OMIT_DEFAULTS = {"gm_smoothing": "savgol"}


def hyperparams_hash_of(args):
    """Short deterministic hash of every HYPERPARAM_ARGS value on `args`. Included in every
    combo_id so that re-running with different hyperparameters against the SAME --models_dir
    gets its OWN separate combo directories, instead of combo_is_done silently treating the
    old run's (now stale, different-hyperparameter) metrics.json as still valid and skipping
    the new one entirely (see the gm1_weight=0.075 vs 0.2 test that motivated this).

    HYPERPARAM_HASH_OMIT_DEFAULTS values are dropped so a knob at its backward-compatible
    default hashes identically to a run from before that knob existed."""
    hp = {name: getattr(args, name) for name in HYPERPARAM_ARGS
          if getattr(args, name) != HYPERPARAM_HASH_OMIT_DEFAULTS.get(name, object())}
    s = json.dumps(hp, sort_keys=True)
    return hashlib.sha1(s.encode()).hexdigest()[:8]


def combo_id_of(f_row, h_row, strategy, hp_hash):
    return f"{f_row['arch_hash']}_{h_row['h_arch_hash']}_{strategy}_{hp_hash}"


def combo_is_done(models_dir, combo_id):
    """The resume/skip check: a combo counts as done iff its metrics.json exists -- no CSV
    is consulted anywhere in `run`. metrics.json is written only after BOTH the LOO folds and
    the full-fit finish for that combo (see _run_combo_batch), so a combo killed mid-training
    (crash, Ctrl+C) has no metrics.json and is correctly retried, never silently treated as done."""
    return os.path.exists(os.path.join(models_dir, combo_id, "metrics.json"))


def _run_combo_batch(combos, data, keys, other_keys, args, hp_hash):
    """Runs the full pipeline (theta_base fit, LOO folds, full-fit) for ONE batch of
    (f_row, h_row, strategy) combos. Writes each combo's own models_dir/<combo_id>/metrics.json
    directly (no results.csv involved at all -- that's built separately, see cmd_populate) and
    returns nothing. --batch_size exists purely to bound ProcessPoolExecutor pool size /
    parallelism grain -- it has no bearing on resumability, since each combo's metrics.json is
    an independent file write, not a buffered/batched one. `hp_hash` (see hyperparams_hash_of)
    is folded into every combo_id so this exact hyperparameter set gets its own directory.

    Also derives a THIRD, "ensemble" pseudo-strategy for every (f_arch_hash, h_arch_hash) pair
    that has BOTH "original" and "delta" combos present in THIS batch: simple average of the
    two strategies' predictions at every point they both have one for (the 5 non-base LOO
    points; all 6 for full-fit), scored the same way. This is exactly what the manual
    scratch_ensemble_original_delta.py analysis did by hand for one saved pair of runs, folded
    into the normal sweep so it comes for free whenever both strategies are (re)trained
    together -- no separate training, no extra models saved (ensemble has none of its own;
    its metrics.json instead records which two combo_ids it was averaged from)."""
    t0 = time.time()

    # --- Step 1: fit theta_base once per DISTINCT f-architecture in this batch needing "delta" ---
    f_archs_needing_base = {f_row["arch_hash"]: f_row for f_row, h_row, strategy in combos
                             if strategy == "delta"}
    theta_base_by_farch = {}
    if f_archs_needing_base:
        with ProcessPoolExecutor(max_workers=args.workers, initializer=_worker_warmup) as ex:
            futs = {
                ex.submit(fit_theta_base_job, arch_hash, json.loads(f_row["architecture"]),
                          int(f_row["n_params"]), data, args.delta_base_epochs, args.delta_base_lr,
                          args.delta_base_lbfgs_epochs, args.lbfgs_max_iter, args.seed,
                          args.weight_decay): arch_hash
                for arch_hash, f_row in f_archs_needing_base.items()
            }
            for fut in as_completed(futs):
                arch_hash, theta_base, base_err = fut.result()
                theta_base_by_farch[arch_hash] = theta_base

    # --- Step 2: submit fold-level jobs (max parallelism) for LOO scoring ---
    fold_futures = {}
    with ProcessPoolExecutor(max_workers=args.workers, initializer=_worker_warmup) as ex:
        for f_row, h_row, strategy in combos:
            architecture = json.loads(f_row["architecture"])
            n_params = int(f_row["n_params"])
            h_hidden, h_layers = int(h_row["h_hidden"]), int(h_row["h_layers"])
            if strategy == "original":
                for held_out in keys:
                    fut = ex.submit(run_fold_original, f_row["arch_hash"], h_row["h_arch_hash"],
                                     architecture, n_params, h_hidden, h_layers, held_out, data,
                                     args.epochs, args.lr, args.gm1_weight, args.lbfgs_epochs,
                                     args.seed, args.weight_decay, args.gm_smoothing)
                    fold_futures[fut] = None
            else:
                theta_base = theta_base_by_farch[f_row["arch_hash"]]
                for held_out in other_keys:
                    fut = ex.submit(run_fold_delta, f_row["arch_hash"], h_row["h_arch_hash"],
                                     architecture, n_params, h_hidden, h_layers, held_out, data,
                                     theta_base, args.epochs, args.lr, args.gm1_weight,
                                     args.delta_reg_weight, args.lbfgs_epochs, args.seed,
                                     args.weight_decay, args.gm_smoothing)
                    fold_futures[fut] = None

        per_combo_errs = {}
        per_combo_preds = {}
        per_combo_gm = {}  # (f_arch, h_arch, strategy) -> {held_out: 4-field gm dict}
        for fut in as_completed(fold_futures):
            f_arch_hash, h_arch_hash, strategy, held_out, err, pred, gm = fut.result()
            key = (f_arch_hash, h_arch_hash, strategy)
            per_combo_errs.setdefault(key, {})[held_out] = err
            per_combo_preds.setdefault(key, {})[held_out] = pred
            if gm is not None:
                per_combo_gm.setdefault(key, {})[held_out] = gm
        print(f"  {len(fold_futures)} LOO folds done ({time.time()-t0:.0f}s)")

    # --- Step 2b: derive "ensemble" LOO scores wherever a (f_arch,h_arch) pair has BOTH
    # "original" and "delta" LOO predictions available from Step 2 above ---
    f_h_pairs_in_batch = {(f_row["arch_hash"], h_row["h_arch_hash"]): (f_row, h_row)
                           for f_row, h_row, strategy in combos}
    for (f_arch_hash, h_arch_hash), (f_row, h_row) in f_h_pairs_in_batch.items():
        key_orig = (f_arch_hash, h_arch_hash, "original")
        key_delta = (f_arch_hash, h_arch_hash, "delta")
        if key_orig in per_combo_preds and key_delta in per_combo_preds:
            shared = set(per_combo_preds[key_orig]) & set(per_combo_preds[key_delta])
            ens_errs, ens_gm = {}, {}
            for held_out in shared:
                pred_ens = (per_combo_preds[key_orig][held_out] + per_combo_preds[key_delta][held_out]) / 2.0
                ens_errs[held_out] = rel_rmse(pred_ens, data[held_out]["Ids"].values.astype(float))
                gm_ens = _gm_rel_rmses_from_pred(data[held_out], pred_ens, GM_VDS_STEP)
                if gm_ens is not None:
                    ens_gm[held_out] = gm_ens
            per_combo_errs[(f_arch_hash, h_arch_hash, "ensemble")] = ens_errs
            if ens_gm:
                per_combo_gm[(f_arch_hash, h_arch_hash, "ensemble")] = ens_gm

    # --- Step 3: full-fit job per combo (for the saved/reconstructable model) ---
    fullfit_by_combo = {}
    with ProcessPoolExecutor(max_workers=args.workers, initializer=_worker_warmup) as ex:
        futs = {}
        for f_row, h_row, strategy in combos:
            architecture = json.loads(f_row["architecture"])
            n_params = int(f_row["n_params"])
            h_hidden, h_layers = int(h_row["h_hidden"]), int(h_row["h_layers"])
            combo_id = combo_id_of(f_row, h_row, strategy, hp_hash)
            save_dir = os.path.join(args.models_dir, combo_id)
            if strategy == "original":
                fut = ex.submit(run_full_fit_original, f_row["arch_hash"], h_row["h_arch_hash"],
                                 architecture, n_params, h_hidden, h_layers, data, args.epochs,
                                 args.lr, args.gm1_weight, args.lbfgs_epochs, args.seed,
                                 args.weight_decay, save_dir, args.gm_smoothing)
            else:
                theta_base = theta_base_by_farch[f_row["arch_hash"]]
                fut = ex.submit(run_full_fit_delta, f_row["arch_hash"], h_row["h_arch_hash"],
                                 architecture, n_params, h_hidden, h_layers, data, theta_base,
                                 args.epochs, args.lr, args.gm1_weight, args.delta_reg_weight,
                                 args.lbfgs_epochs, args.seed, args.weight_decay, save_dir,
                                 args.gm_smoothing)
            futs[fut] = (f_row, h_row, strategy, combo_id, save_dir)
        fullfit_preds_by_key = {}  # (f_arch_hash, h_arch_hash, strategy) -> {qpoint: pred}
        for fut in as_completed(futs):
            f_row, h_row, strategy, combo_id, save_dir = futs[fut]
            try:
                f_arch_hash, h_arch_hash, _, full_fit_mean, preds = fut.result()
                fullfit_by_combo[combo_id] = (full_fit_mean, save_dir, None)
                fullfit_preds_by_key[(f_arch_hash, h_arch_hash, strategy)] = preds
            except Exception as e:
                fullfit_by_combo[combo_id] = (float("nan"), save_dir, str(e))
        print(f"  {len(futs)} full-fit models saved ({time.time()-t0:.0f}s)")

    # --- Step 3b: derive "ensemble" full-fit scores the same way as Step 2b, over all 6 points
    # (both strategies' full-fit covers all 6 -- "delta" evaluates at BASE_KEY too, where its
    # own delta_theta should be ~0 by construction) ---
    ensemble_fullfit_mean = {}
    for (f_arch_hash, h_arch_hash), (f_row, h_row) in f_h_pairs_in_batch.items():
        key_orig = (f_arch_hash, h_arch_hash, "original")
        key_delta = (f_arch_hash, h_arch_hash, "delta")
        if key_orig in fullfit_preds_by_key and key_delta in fullfit_preds_by_key:
            shared = set(fullfit_preds_by_key[key_orig]) & set(fullfit_preds_by_key[key_delta])
            fit_errs = []
            for k in shared:
                pred_ens = (fullfit_preds_by_key[key_orig][k] + fullfit_preds_by_key[key_delta][k]) / 2.0
                fit_errs.append(rel_rmse(pred_ens, data[k]["Ids"].values.astype(float)))
            ensemble_fullfit_mean[(f_arch_hash, h_arch_hash)] = float(np.mean(fit_errs)) if fit_errs else float("nan")

    # --- Step 4: write each combo's OWN metrics.json into its OWN save_dir. No results.csv,
    # no shared/buffered state -- each write is independent, so a crash here only leaves the
    # combos not yet written as "not done" (they simply have no metrics.json yet), exactly
    # like a combo whose training itself hadn't finished. Nothing here stores any path (see
    # combo_is_done / cmd_populate): a combo's own directory name is already self-describing.
    n_done = 0
    for f_row, h_row, strategy in combos:
        combo_id = combo_id_of(f_row, h_row, strategy, hp_hash)
        key = (f_row["arch_hash"], h_row["h_arch_hash"], strategy)
        errs_by_point = per_combo_errs.get(key, {})
        n_expected = len(keys) if strategy == "original" else len(other_keys)
        status = "ok" if len(errs_by_point) == n_expected else "incomplete"
        errs = list(errs_by_point.values())
        full_fit_mean, save_dir, err_msg = fullfit_by_combo.get(combo_id, (float("nan"), "", "missing"))
        metrics = dict(
            combo_id=combo_id,
            f_arch_hash=f_row["arch_hash"],
            h_arch_hash=h_row["h_arch_hash"],
            strategy=strategy,
            hp_hash=hp_hash,
            gm1_weight=args.gm1_weight,
            gm_smoothing=args.gm_smoothing,
            delta_reg_weight=args.delta_reg_weight if strategy == "delta" else "",
            weight_decay=args.weight_decay,
            epochs=args.epochs,
            lr=args.lr,
            lbfgs_epochs=args.lbfgs_epochs,
            lbfgs_max_iter=args.lbfgs_max_iter,
            delta_base_epochs=args.delta_base_epochs if strategy == "delta" else "",
            delta_base_lr=args.delta_base_lr if strategy == "delta" else "",
            delta_base_lbfgs_epochs=args.delta_base_lbfgs_epochs if strategy == "delta" else "",
            seed=args.seed,
            n_params_f=f_row["n_params"],
            h_hidden=h_row["h_hidden"],
            h_layers=h_row["h_layers"],
            loo_mean_rel_rmse=float(np.mean(errs)) if errs else None,
            loo_n_points=len(errs),
            loo_worst_rel_rmse=float(np.max(errs)) if errs else None,
            full_fit_mean_rel_rmse=full_fit_mean,
            # LOO gm1/gm2/gm3 (+combined), mean over held-out folds -- {} (-> blank) if no fold
            # scored gm. Computed at fold time while each fold model was still in memory.
            **_mean_gm_over_points(per_combo_gm.get(key, {}), prefix="loo_"),
            loo_per_point=({qtag_local(*k): v for k, v in errs_by_point.items()}),
            status=status if err_msg is None else "error",
            error_msg=err_msg or "",
            wall_time_seconds=round(time.time() - t0, 1),
            timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
        )
        if save_dir:
            os.makedirs(save_dir, exist_ok=True)
            with open(os.path.join(save_dir, "metrics.json"), "w") as mf:
                json.dump(metrics, mf, indent=2)
            n_done += 1

    # --- Step 4b: same write, for every "ensemble" pair derived in Steps 2b/3b. No weights are
    # saved for "ensemble" (it has none of its own) -- source_original_combo_id/
    # source_delta_combo_id in its metrics.json point at the two real combos to reload+average
    # if the ensemble prediction itself needs to be reconstructed later. ---
    n_ensemble = 0
    for key in [k for k in per_combo_errs if k[2] == "ensemble"]:
        f_arch_hash, h_arch_hash, _ = key
        f_row, h_row = f_h_pairs_in_batch[(f_arch_hash, h_arch_hash)]
        combo_id = combo_id_of(f_row, h_row, "ensemble", hp_hash)
        save_dir = os.path.join(args.models_dir, combo_id)
        errs_by_point = per_combo_errs[key]
        errs = list(errs_by_point.values())
        metrics = dict(
            combo_id=combo_id,
            f_arch_hash=f_arch_hash,
            h_arch_hash=h_arch_hash,
            strategy="ensemble",
            hp_hash=hp_hash,
            source_original_combo_id=combo_id_of(f_row, h_row, "original", hp_hash),
            source_delta_combo_id=combo_id_of(f_row, h_row, "delta", hp_hash),
            gm1_weight=args.gm1_weight,
            gm_smoothing=args.gm_smoothing,
            delta_reg_weight=args.delta_reg_weight,
            weight_decay=args.weight_decay,
            epochs=args.epochs,
            lr=args.lr,
            lbfgs_epochs=args.lbfgs_epochs,
            lbfgs_max_iter=args.lbfgs_max_iter,
            delta_base_epochs=args.delta_base_epochs,
            delta_base_lr=args.delta_base_lr,
            delta_base_lbfgs_epochs=args.delta_base_lbfgs_epochs,
            seed=args.seed,
            n_params_f=f_row["n_params"],
            h_hidden=h_row["h_hidden"],
            h_layers=h_row["h_layers"],
            loo_mean_rel_rmse=float(np.mean(errs)) if errs else None,
            loo_n_points=len(errs),
            loo_worst_rel_rmse=float(np.max(errs)) if errs else None,
            full_fit_mean_rel_rmse=ensemble_fullfit_mean.get((f_arch_hash, h_arch_hash), float("nan")),
            # LOO gm of the ENSEMBLE = gm of the averaged (original+delta) held-out Ids curve
            # per fold, mean over folds (Step 2b). {} -> blank if unavailable.
            **_mean_gm_over_points(per_combo_gm.get(key, {}), prefix="loo_"),
            loo_per_point=({qtag_local(*k): v for k, v in errs_by_point.items()}),
            status="ok" if len(errs_by_point) == len(other_keys) else "incomplete",
            error_msg="",
            wall_time_seconds=round(time.time() - t0, 1),
            timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
        )
        os.makedirs(save_dir, exist_ok=True)
        with open(os.path.join(save_dir, "metrics.json"), "w") as mf:
            json.dump(metrics, mf, indent=2)
        n_ensemble += 1

    print(f"  {n_done} metrics.json files written, plus {n_ensemble} more 'ensemble' ones "
          f"(no weights, {n_done + n_ensemble} total)")


def cmd_run(args):
    """ONLY trains and writes files under --models_dir/<combo_id>/ -- never touches any CSV.
    Processes f-architectures in batches of --batch_size purely for ProcessPoolExecutor
    parallelism grain. Resume/skip logic scans the filesystem (combo_is_done: does that
    combo's metrics.json exist?), so:
      - Pausing: Ctrl+C at any point is safe -- re-running the exact same command later skips
        every combo whose metrics.json already exists and only (re)trains the rest. At most
        the combos that were mid-training when killed need to be redone.
      - Moving machines mid-sweep: copy --models_dir (however far it's gotten) to the other
        computer, then run the same `run` command there pointing --models_dir at the copied
        location and --csv_dir at wherever the measurement data lives on that machine -- it
        resumes from the same already-done set. configs/arch_search_1000/'s
        f_architectures.csv/h_architectures.csv are committed to the repo, so arch_hash values
        match exactly on both machines as long as both cloned the same commit.
      - Building results.csv from what's done so far (any time, without retraining): see the
        separate `populate` subcommand.
    """
    f_rows_all = read_csv(args.f_csv)
    if args.n_f_architectures is not None:
        f_rows_all = f_rows_all[:args.n_f_architectures]
    h_rows = read_csv(args.h_csv)
    hp_hash = hyperparams_hash_of(args)
    print(f"Loaded {len(f_rows_all)} f-architectures from {args.f_csv}, "
          f"{len(h_rows)} H-architectures from {args.h_csv}")
    print(f"Hyperparameter hash for this run: {hp_hash} "
          f"({ {name: getattr(args, name) for name in HYPERPARAM_ARGS} })")
    print(f"Resume check is filesystem-based: a combo is skipped if "
          f"{args.models_dir}/<combo_id>/metrics.json already exists -- combo_id includes "
          f"{hp_hash}, so a DIFFERENT hyperparameter set never collides with or hides this one.")

    data = load_all(args.csv_dir)
    keys = sorted(data.keys())
    other_keys = [k for k in keys if k != BASE_KEY]
    print("Quiescent points found:", keys, " BASE_KEY:", BASE_KEY)

    n_batches = (len(f_rows_all) + args.batch_size - 1) // args.batch_size
    t_start = time.time()
    total_done = 0
    total_skipped = 0
    for b in range(n_batches):
        f_rows_batch = f_rows_all[b * args.batch_size:(b + 1) * args.batch_size]
        combos, skipped = [], 0
        for f_row in f_rows_batch:
            for h_row in h_rows:
                for strategy in ("original", "delta"):
                    combo_id = combo_id_of(f_row, h_row, strategy, hp_hash)
                    if combo_is_done(args.models_dir, combo_id):
                        skipped += 1
                    else:
                        combos.append((f_row, h_row, strategy))
        total_skipped += skipped
        if not combos:
            continue
        print(f"\n--- Batch {b+1}/{n_batches}: {len(f_rows_batch)} f-architectures, "
              f"{len(combos)} new combos, {skipped} already done ({time.time()-t_start:.0f}s elapsed total) ---")
        _run_combo_batch(combos, data, keys, other_keys, args, hp_hash)
        total_done += len(combos)

    print(f"\nDone. Trained {total_done} new combos this run ({total_skipped} were already done "
          f"and skipped). All results are under {args.models_dir}/<combo_id>/.")
    print(f"Run `python {os.path.basename(__file__)} populate --models_dir {args.models_dir} "
          f"--results_csv <path>` to build/refresh results.csv from what's done so far.")


def qtag_local(vgsq, vdsq):
    return f"Vgsq{vgsq:g}_Vdsq{vdsq:g}"


# ====================== gm1/gm2/gm3 metrics (optional `populate --with_gm` add-on) ======================
#
# The sweep's metrics.json only scores Ids (rel_rmse of predicted vs measured drain current).
# `populate --with_gm` ALSO reloads each combo's saved FULL-FIT model and scores the
# transconductance derivatives against the measured data:
#     gm1 = dIds/dVgs,  gm2 = d2Ids/dVgs2,  gm3 = d3Ids/dVgs3
# plus combined_gm = equal-weight mean of the three per-order rel-RMSEs.
#
# Only the full-fit model is scored -- it's the only set of weights saved per combo (the LOO
# folds aren't kept). Derivatives use the SAME Savitzky-Golay estimator as the gm1 training
# target (signal_utils.smooth_derivative), taken on transfer curves (Ids vs Vgs at ~fixed Vds)
# assembled exactly like train_loo.build_gm_targets. The model is evaluated at the SAME
# (Vgs, Vds) sample points as the measurement, so measured/predicted derivatives share one grid
# and rel_rmse compares equal-length vectors. Each per-order rel-RMSE is concatenated across the
# transfer curves, then averaged over the 6 quiescent points (same as full_fit_mean_rel_rmse).
#
# Each combo's result is cached in --models_dir/<combo_id>/gm_metrics.json so re-running populate
# is cheap; pass --recompute_gm to force a refresh. gm2/gm3 in particular are noisier than gm1
# (2nd/3rd numerical derivative of ~35 matched points), so treat them as coarse indicators.

GM_METRICS_FIELDS = ["gm1_rel_rmse", "gm2_rel_rmse", "gm3_rel_rmse", "combined_gm_rel_rmse"]
# LOO counterparts (held-out points, mean over folds). Written natively into metrics.json at
# fold time by `run` (Option C), and/or into a loo_gm_metrics.json sidecar by
# `populate --with_loo_gm` retraining the folds of the top-N combos (Option A).
LOO_GM_METRICS_FIELDS = ["loo_" + f for f in GM_METRICS_FIELDS]
# GM_VDS_STEP (spacing in V of the transfer-curve Vds levels) is imported from signal_utils
# so this metric and the gm1 training target build their curves on the exact same grid.

_GM_DATA = None  # per-process measurement-data cache, set by _gm_worker_init


def _gm_worker_init(csv_dir):
    global _GM_DATA
    torch.set_num_threads(1)
    _GM_DATA = load_all(csv_dir)


def _assemble_transfer_curves(df, vds_step=GM_VDS_STEP):
    """One (vgs, vds, ids, row_pos) transfer curve (Ids vs Vgs at ~fixed Vds) per target Vds --
    nearest real point per TN group, same construction as train_loo.build_gm_targets (target
    Vds levels = gm_vds_target_list(vds_lo, vds_hi, vds_step)). Arrays are Vgs-sorted; values
    are raw (volts / amps). row_pos = positional index into df of each picked point, so a
    prediction array aligned 1:1 with df rows (a saved fold pred, an averaged ensemble pred)
    can be sampled at exactly the same points."""
    df = df.reset_index(drop=True)  # -> label == position, so idxmin() gives a positional index
    groups = [g.sort_values("Vds") for _, g in df.groupby("TN")]
    vds_lo, vds_hi = df["Vds"].min(), df["Vds"].max()
    curves = []
    for t_vds in gm_vds_target_list(vds_lo, vds_hi, vds_step):
        vgs_pts, vds_pts, ids_pts, pos = [], [], [], []
        for g in groups:
            idx = (g["Vds"] - t_vds).abs().idxmin()
            vgs_pts.append(g.loc[idx, "Vgs"])
            vds_pts.append(g.loc[idx, "Vds"])
            ids_pts.append(g.loc[idx, "Ids"])
            pos.append(int(idx))
        vgs_pts, vds_pts, ids_pts, pos = (np.array(vgs_pts), np.array(vds_pts),
                                          np.array(ids_pts), np.array(pos))
        order = np.argsort(vgs_pts)
        curves.append((vgs_pts[order], vds_pts[order], ids_pts[order], pos[order]))
    return curves


def _gm_rel_rmses_core(df, vds_step, ids_model_getter):
    """ids_model_getter(vgs_pts, vds_pts, row_pos) -> predicted Ids at those transfer-curve
    points. Returns the 4 gm rel-RMSE fields for ONE quiescent point (each per-order value
    concatenated across all transfer curves), or None if no curve had enough points."""
    true_c, pred_c = {1: [], 2: [], 3: []}, {1: [], 2: [], 3: []}
    for vgs_pts, vds_pts, ids_pts, pos in _assemble_transfer_curves(df, vds_step):
        if len(vgs_pts) < 5:
            continue
        ids_model = np.asarray(ids_model_getter(vgs_pts, vds_pts, pos), dtype=float)
        for o in (1, 2, 3):
            true_c[o].append(smooth_derivative(vgs_pts, ids_pts, order=o))
            pred_c[o].append(smooth_derivative(vgs_pts, ids_model, order=o))
    if not true_c[1]:
        return None
    out = {}
    for o in (1, 2, 3):
        out[f"gm{o}_rel_rmse"] = rel_rmse(np.concatenate(pred_c[o]), np.concatenate(true_c[o]))
    out["combined_gm_rel_rmse"] = float(np.mean([out[f"gm{o}_rel_rmse"] for o in (1, 2, 3)]))
    return out


def _gm_rel_rmses_one_qpoint(df, predict_ids, vds_step):
    """gm rel-RMSEs for ONE quiescent point from a model callable: predict_ids(vgs_raw_np,
    vds_raw_np) -> ids_np (raw volts in, amps out)."""
    return _gm_rel_rmses_core(df, vds_step, lambda vg, vd, pos: predict_ids(vg, vd))


def _gm_rel_rmses_from_pred(df, ids_pred_full, vds_step):
    """gm rel-RMSEs for ONE quiescent point from a prediction array aligned 1:1 with df rows
    (a saved LOO fold prediction, or an averaged ensemble prediction) -- no model needed."""
    ids_pred_full = np.asarray(ids_pred_full, dtype=float)
    return _gm_rel_rmses_core(df, vds_step, lambda vg, vd, pos: ids_pred_full[pos])


def _mean_gm_over_points(gm_by_point, prefix=""):
    """gm_by_point: {held_out_key: <4-field gm dict>}. -> {prefix+field: mean over points},
    or {} if empty. NaNs propagate (np.mean of a NaN-containing list is NaN)."""
    if not gm_by_point:
        return {}
    vals = list(gm_by_point.values())
    return {prefix + f: float(np.mean([v[f] for v in vals])) for f in GM_METRICS_FIELDS}


def _predict_ids_fn(net, architecture, vgsq, vdsq, theta_base=None):
    """Ids(vgs_raw_np, vds_raw_np) -> ids_np for a fixed quiescent point, from a HyperNetwork
    (or H_comp + theta_base) already in memory. Same normalization as the training code."""
    net.eval()
    qpoint = torch.tensor([vgsq / VGS_SCALE, vdsq / VDS_SCALE], dtype=torch.float32)

    def predict(vgs_raw_np, vds_raw_np):
        vgs_t = torch.tensor(np.asarray(vgs_raw_np) / VGS_SCALE, dtype=torch.float32)
        vds_t = torch.tensor(np.asarray(vds_raw_np) / VDS_SCALE, dtype=torch.float32)
        with torch.no_grad():
            theta = net(qpoint)
            if theta_base is not None:
                theta = theta_base + theta
            return main_net_forward(theta, vgs_t, vds_t, architecture).numpy()
    return predict


def _make_combo_predictor(models_dir, combo_id):
    """-> predict(vgsq, vdsq, vgs_raw_np, vds_raw_np) -> ids_np for this combo's FULL-FIT model.
    'ensemble' combos have no weights of their own -- they recurse into their two source combos
    (from metrics.json) and average the two Ids predictions, exactly as the sweep scored them."""
    d = os.path.join(models_dir, combo_id)
    metrics = json.load(open(os.path.join(d, "metrics.json")))
    strategy = metrics["strategy"]

    if strategy == "ensemble":
        orig_pred = _make_combo_predictor(models_dir, metrics["source_original_combo_id"])
        delta_pred = _make_combo_predictor(models_dir, metrics["source_delta_combo_id"])
        return lambda vgsq, vdsq, vgs, vds: 0.5 * (orig_pred(vgsq, vdsq, vgs, vds)
                                                    + delta_pred(vgsq, vdsq, vgs, vds))

    meta = json.load(open(os.path.join(d, "meta.json")))
    architecture = meta["architecture"]
    n_params = int(meta["n_params"])
    net = HyperNetwork(n_params, hidden=int(meta["h_hidden"]),
                        n_hidden_layers=int(meta["h_layers"]), n_in=2)
    theta_base = None
    if strategy == "original":
        net.load_state_dict(torch.load(os.path.join(d, "hyper_full.pt"), map_location="cpu",
                                        weights_only=True))
    else:  # delta: theta_total = theta_base + H_comp(qpoint)
        net.load_state_dict(torch.load(os.path.join(d, "hcomp_full.pt"), map_location="cpu",
                                        weights_only=True))
        theta_base = torch.load(os.path.join(d, "theta_base.pt"), map_location="cpu",
                                 weights_only=True)
    net.eval()

    def predict(vgsq, vdsq, vgs_raw_np, vds_raw_np):
        qpoint = torch.tensor([vgsq / VGS_SCALE, vdsq / VDS_SCALE], dtype=torch.float32)
        vgs_t = torch.tensor(np.asarray(vgs_raw_np) / VGS_SCALE, dtype=torch.float32)
        vds_t = torch.tensor(np.asarray(vds_raw_np) / VDS_SCALE, dtype=torch.float32)
        with torch.no_grad():
            theta = net(qpoint)
            if theta_base is not None:
                theta = theta_base + theta
            return main_net_forward(theta, vgs_t, vds_t, architecture).numpy()
    return predict


def _gm_metrics_for_combo(models_dir, combo_id, data, vds_step):
    """Mean over the 6 quiescent points of each per-order gm rel-RMSE. NaN if no point scored."""
    predict = _make_combo_predictor(models_dir, combo_id)
    per_q = []
    for (vgsq, vdsq), df in data.items():
        r = _gm_rel_rmses_one_qpoint(
            df, lambda vg, vd, _q=(vgsq, vdsq): predict(_q[0], _q[1], vg, vd), vds_step)
        if r is not None:
            per_q.append(r)
    return {f: (float(np.mean([r[f] for r in per_q])) if per_q else float("nan"))
            for f in GM_METRICS_FIELDS}


def _gm_job(task):
    models_dir, combo_id, vds_step = task
    try:
        agg = _gm_metrics_for_combo(models_dir, combo_id, _GM_DATA, vds_step)
        with open(os.path.join(models_dir, combo_id, "gm_metrics.json"), "w") as f:
            json.dump(agg, f, indent=2)
        return combo_id, None
    except Exception as e:  # one bad combo shouldn't abort the whole pass
        return combo_id, repr(e)


def run_gm_metrics_pass(models_dir, combo_ids, csv_dir, workers, vds_step, recompute):
    """Fill --models_dir/<combo_id>/gm_metrics.json for every combo that lacks one (or all, with
    recompute=True). This is the ONLY part of `populate` that touches PyTorch / the measurement
    data -- guarded behind --with_gm precisely so the plain `populate` stays torch-free."""
    todo = [(models_dir, c, vds_step) for c in combo_ids
            if recompute or not os.path.exists(os.path.join(models_dir, c, "gm_metrics.json"))]
    n_cached = len(combo_ids) - len(todo)
    if not todo:
        print(f"  gm metrics: all {len(combo_ids)} combos already cached "
              f"(pass --recompute_gm to refresh)")
        return
    print(f"  gm metrics: computing {len(todo)} combos ({n_cached} cached) with {workers} worker(s)...")
    t0, n_err, shown = time.time(), 0, 0
    def report(i, cid, err):
        nonlocal n_err, shown
        if err:
            n_err += 1
            if shown < 10:
                print(f"    ERROR [{cid}]: {err}")
                shown += 1
        if i % 500 == 0:
            print(f"    {i}/{len(todo)} ({time.time() - t0:.0f}s)")
    if workers <= 1:
        _gm_worker_init(csv_dir)
        for i, task in enumerate(todo, 1):
            cid, err = _gm_job(task)
            report(i, cid, err)
    else:
        with ProcessPoolExecutor(max_workers=workers, initializer=_gm_worker_init,
                                  initargs=(csv_dir,)) as ex:
            futs = [ex.submit(_gm_job, task) for task in todo]
            for i, fut in enumerate(as_completed(futs), 1):
                cid, err = fut.result()
                report(i, cid, err)
    print(f"  gm metrics: done ({time.time() - t0:.0f}s, {n_err} error(s))")


# ---------------------- LOO gm (Option A: retrain the top-N combos' folds) ----------------------
#
# The sweep never saved the per-fold LOO models (only the full-fit weights), so LOO gm cannot be
# recovered from disk -- the folds have to be retrained. `populate --with_loo_gm` does that for
# the top-N combos by loo_mean_rel_rmse only (retraining all 12000 would ~= re-running the sweep),
# reusing run_fold_original / run_fold_delta with each combo's own saved hyperparameters. The
# per-order rel-RMSE on each held-out point is averaged over folds into loo_gm*_rel_rmse and
# cached in <combo_id>/loo_gm_metrics.json. 'ensemble' targets retrain BOTH their source combos'
# folds and score gm on the averaged held-out Ids curve (same as the sweep's ensemble Ids score).

def _loo_gm_fold_spec(models_dir, combo_id, m):
    """Everything run_fold_{original,delta} needs to re-run ONE fold of `combo_id` exactly as
    `run` did: architecture from meta.json, hyperparameters from its own metrics.json (`m`)."""
    meta = json.load(open(os.path.join(models_dir, combo_id, "meta.json")))
    strat = m["strategy"]
    spec = dict(kind=strat, architecture=meta["architecture"], n_params=int(meta["n_params"]),
                h_hidden=int(meta["h_hidden"]), h_layers=int(meta["h_layers"]),
                f_arch_hash=m["f_arch_hash"], h_arch_hash=m["h_arch_hash"],
                epochs=int(m["epochs"]), lr=float(m["lr"]), gm1_weight=float(m["gm1_weight"]),
                lbfgs_epochs=int(m["lbfgs_epochs"]), seed=int(m["seed"]),
                weight_decay=float(m["weight_decay"]),
                gm_smoothing=m.get("gm_smoothing", "savgol"))
    if strat == "delta":
        spec["delta_reg_weight"] = float(m["delta_reg_weight"])
        spec["theta_base_path"] = os.path.join(models_dir, combo_id, "theta_base.pt")
    return spec


def _loo_gm_worker_init(csv_dir):
    _worker_warmup()       # same AdamW-import warm-up the sweep's fold pool uses
    _gm_worker_init(csv_dir)


def _loo_gm_fold_job(spec):
    """Retrain one fold and return (weights_combo_id, held_out, held_out_pred, gm_dict_or_None)."""
    held_out = tuple(spec["held_out"])
    if spec["kind"] == "original":
        res = run_fold_original(spec["f_arch_hash"], spec["h_arch_hash"], spec["architecture"],
                                 spec["n_params"], spec["h_hidden"], spec["h_layers"], held_out,
                                 _GM_DATA, spec["epochs"], spec["lr"], spec["gm1_weight"],
                                 spec["lbfgs_epochs"], spec["seed"], spec["weight_decay"],
                                 spec["gm_smoothing"])
    else:
        theta_base = torch.load(spec["theta_base_path"], map_location="cpu", weights_only=True)
        res = run_fold_delta(spec["f_arch_hash"], spec["h_arch_hash"], spec["architecture"],
                              spec["n_params"], spec["h_hidden"], spec["h_layers"], held_out,
                              _GM_DATA, theta_base, spec["epochs"], spec["lr"], spec["gm1_weight"],
                              spec["delta_reg_weight"], spec["lbfgs_epochs"], spec["seed"],
                              spec["weight_decay"], spec["gm_smoothing"])
    _, _, _, _, _err, pred, gm = res
    return spec["weights_combo_id"], held_out, pred, gm


def run_loo_gm_pass(models_dir, target_combo_ids, metrics_by_combo, csv_dir, workers,
                     vds_step, recompute):
    """Retrain LOO folds for `target_combo_ids` and write each a <combo_id>/loo_gm_metrics.json."""
    pending = [c for c in target_combo_ids
               if recompute or not os.path.exists(os.path.join(models_dir, c, "loo_gm_metrics.json"))]
    n_cached = len(target_combo_ids) - len(pending)
    if not pending:
        print(f"  loo gm: all {len(target_combo_ids)} target combos already cached "
              f"(pass --recompute_gm to refresh)")
        return

    data = load_all(csv_dir)
    keys = sorted(data.keys())
    other_keys = [k for k in keys if k != BASE_KEY]

    specs, target_plan, skipped = {}, {}, []
    for c in pending:
        m = metrics_by_combo[c]
        try:
            if m["strategy"] in ("original", "delta"):
                base = _loo_gm_fold_spec(models_dir, c, m)
                for ho in (keys if m["strategy"] == "original" else other_keys):
                    specs.setdefault((c, ho), {**base, "weights_combo_id": c, "held_out": ho})
                target_plan[c] = ("simple", c)
            else:  # ensemble
                oid, did = m["source_original_combo_id"], m["source_delta_combo_id"]
                if oid not in metrics_by_combo or did not in metrics_by_combo:
                    skipped.append((c, "source original/delta combo not present"))
                    continue
                ospec = _loo_gm_fold_spec(models_dir, oid, metrics_by_combo[oid])
                dspec = _loo_gm_fold_spec(models_dir, did, metrics_by_combo[did])
                for ho in keys:
                    specs.setdefault((oid, ho), {**ospec, "weights_combo_id": oid, "held_out": ho})
                for ho in other_keys:
                    specs.setdefault((did, ho), {**dspec, "weights_combo_id": did, "held_out": ho})
                target_plan[c] = ("ensemble", oid, did)
        except Exception as e:
            skipped.append((c, repr(e)))

    spec_list = list(specs.values())
    print(f"  loo gm: {len(target_plan)} target combos ({n_cached} cached, {len(skipped)} skipped) "
          f"-> {len(spec_list)} fold retrains with {workers} worker(s)...")
    t0 = time.time()
    preds, gms = {}, {}

    def stash(wc, ho, pred, gm):
        preds.setdefault(wc, {})[ho] = pred
        if gm is not None:
            gms.setdefault(wc, {})[ho] = gm

    if workers <= 1:
        _loo_gm_worker_init(csv_dir)
        for i, spec in enumerate(spec_list, 1):
            wc, ho, pred, gm = _loo_gm_fold_job(spec)
            stash(wc, ho, pred, gm)
            if i % 50 == 0:
                print(f"    {i}/{len(spec_list)} folds ({time.time() - t0:.0f}s)")
    else:
        with ProcessPoolExecutor(max_workers=workers, initializer=_loo_gm_worker_init,
                                  initargs=(csv_dir,)) as ex:
            futs = [ex.submit(_loo_gm_fold_job, spec) for spec in spec_list]
            for i, fut in enumerate(as_completed(futs), 1):
                wc, ho, pred, gm = fut.result()
                stash(wc, ho, pred, gm)
                if i % 50 == 0:
                    print(f"    {i}/{len(spec_list)} folds ({time.time() - t0:.0f}s)")

    n_written = 0
    for c, plan in target_plan.items():
        if plan[0] == "simple":
            agg = _mean_gm_over_points(gms.get(plan[1], {}), prefix="loo_")
        else:
            _, oid, did = plan
            po, pd = preds.get(oid, {}), preds.get(did, {})
            per_point = {}
            for ho in set(po) & set(pd):
                r = _gm_rel_rmses_from_pred(data[ho], (po[ho] + pd[ho]) / 2.0, vds_step)
                if r is not None:
                    per_point[ho] = r
            agg = _mean_gm_over_points(per_point, prefix="loo_")
        if agg:
            with open(os.path.join(models_dir, c, "loo_gm_metrics.json"), "w") as f:
                json.dump(agg, f, indent=2)
            n_written += 1

    print(f"  loo gm: done ({time.time() - t0:.0f}s) -- wrote {n_written} loo_gm_metrics.json")
    for c, why in skipped[:10]:
        print(f"    skipped {c}: {why}")


def cmd_populate(args):
    """Read-only aggregation pass, no training: scans every --models_dir/<combo_id>/
    metrics.json it can find and (re)builds results.csv from scratch (one row per combo that
    has a metrics.json -- combos still mid-training or never started are simply absent, not
    an error). Safe to run at any time, as many times as you like, from any machine that has
    --models_dir available (moved/copied or original location).

    Plain `populate` never touches PyTorch or the measurement data (doesn't need --csv_dir).
    Two opt-in add-ons DO load torch + the CSVs (--csv_dir):
      --with_gm      score gm1/gm2/gm3 (+combined_gm) rel-RMSE of each combo's FULL-FIT model,
                     cached in <combo_id>/gm_metrics.json.
      --with_loo_gm  the LOO counterpart (loo_gm*_rel_rmse) -- but the per-fold models weren't
                     saved, so this RETRAINS the folds of the top --loo_gm_top combos (by
                     loo_mean_rel_rmse) only, caching in <combo_id>/loo_gm_metrics.json.
    Combos that `run` produced after this change already carry loo_gm* natively in metrics.json."""
    if not os.path.isdir(args.models_dir):
        print(f"{args.models_dir} does not exist -- nothing to populate.")
        return

    combo_dirs = sorted(d for d in os.listdir(args.models_dir)
                         if os.path.isdir(os.path.join(args.models_dir, d)))
    done, metrics_by_combo = [], {}
    for c in combo_dirs:
        mp = os.path.join(args.models_dir, c, "metrics.json")
        if not os.path.exists(mp):
            continue  # directory exists (training started) but didn't finish -- not an error
        with open(mp) as f:
            metrics_by_combo[c] = json.load(f)
        done.append(c)

    if args.with_gm:
        run_gm_metrics_pass(args.models_dir, done, args.csv_dir, args.gm_workers,
                             args.gm_vds_step, args.recompute_gm)

    if args.with_loo_gm:
        ranked = sorted((c for c in done
                          if isinstance(metrics_by_combo[c].get("loo_mean_rel_rmse"), (int, float))),
                         key=lambda c: metrics_by_combo[c]["loo_mean_rel_rmse"])
        run_loo_gm_pass(args.models_dir, ranked[:args.loo_gm_top], metrics_by_combo, args.csv_dir,
                         args.gm_workers, args.gm_vds_step, args.recompute_gm)

    def _clean(v):
        return "" if v == "" or v is None or (isinstance(v, float) and np.isnan(v)) else v

    rows = []
    for combo_id in done:
        m = metrics_by_combo[combo_id]
        row = {field: m.get(field, "") for field in RESULTS_CSV_FIELDS}
        row["loo_per_point_json"] = json.dumps(m.get("loo_per_point", {}))
        row["model_dir"] = combo_id  # relative to --models_dir itself -- always portable

        for sidecar, sc_fields in (("gm_metrics.json", GM_METRICS_FIELDS),
                                    ("loo_gm_metrics.json", LOO_GM_METRICS_FIELDS)):
            sp = os.path.join(args.models_dir, combo_id, sidecar)
            if os.path.exists(sp):
                with open(sp) as f:
                    sc = json.load(f)
                for field in sc_fields:
                    if field in sc:
                        row[field] = _clean(sc[field])
        for field in RESULTS_CSV_FIELDS:  # normalise NaN/None coming straight from metrics.json
            row[field] = _clean(row[field])
        rows.append(row)

    dirname = os.path.dirname(os.path.abspath(args.results_csv))
    os.makedirs(dirname, exist_ok=True)
    write_csv(args.results_csv, rows, RESULTS_CSV_FIELDS)
    n_gm = sum(1 for r in rows if r.get("gm1_rel_rmse") not in ("", None))
    n_loo_gm = sum(1 for r in rows if r.get("loo_gm1_rel_rmse") not in ("", None))
    print(f"Scanned {len(combo_dirs)} combo directories under {args.models_dir} "
          f"({len(rows)} had a complete metrics.json) -> wrote {len(rows)} rows to {args.results_csv}")
    print(f"  gm* (full-fit) filled for {n_gm}/{len(rows)} rows; "
          f"loo_gm* (held-out) filled for {n_loo_gm}/{len(rows)} rows.")
    if not n_gm:
        print("  -> pass `--with_gm --csv_dir <dir>` for full-fit gm; "
              "`--with_loo_gm` (retrains top-N folds) for LOO gm.")


# ============================== CLI ==============================

def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    g = sub.add_parser("generate", help="Write f_architectures.csv and h_architectures.csv")
    g.add_argument("--f_csv", default="configs/arch_search_1000/f_architectures.csv")
    g.add_argument("--h_csv", default="configs/arch_search_1000/h_architectures.csv")
    g.add_argument("--n_f_architectures", type=int, default=1000,
                    help="Ignored with --enumerate_all.")
    g.add_argument("--n_tanh_only", type=int, default=150,
                    help="Ignored with --enumerate_all.")
    g.add_argument("--min_layers", type=int, default=1)
    g.add_argument("--max_layers", type=int, default=3)
    g.add_argument("--min_neurons", type=int, default=6, help="Neurons per LAYER (lower bound).")
    g.add_argument("--max_neurons", type=int, default=16, help="Neurons per LAYER (upper bound).")
    g.add_argument("--min_neurons_total", type=int, default=None,
                    help="Optional lower bound on the WHOLE main-net's neuron count (sum over layers).")
    g.add_argument("--max_neurons_total", type=int, default=None,
                    help="Optional upper bound on the whole main-net's neuron count.")
    g.add_argument("--enumerate_all", action="store_true",
                    help="Full enumeration instead of sampling: every size-tuple satisfying the "
                         "per-layer AND total bounds, each as 100%% tanh + one arch per weight "
                         f"triple {DEFAULT_ACTIVATION_WEIGHTS} and {FALLBACK_ACTIVATION_WEIGHTS} "
                         "(collapsed by hash -- small layers give identical compositions). "
                         "Ignores --n_f_architectures/--n_tanh_only/--seed.")
    g.add_argument("--h_base_hidden", type=int, default=32)
    g.add_argument("--h_base_layers", type=int, default=1)
    g.add_argument("--seed", type=int, default=42)
    g.set_defaults(func=cmd_generate)

    r = sub.add_parser("run", help="Train combos, writing only to --models_dir/<combo_id>/ (no CSV)")
    r.add_argument("--csv_dir", default=r"C:\Users\acost\repos\csvs")
    r.add_argument("--f_csv", default="configs/arch_search_1000/f_architectures.csv")
    r.add_argument("--h_csv", default="configs/arch_search_1000/h_architectures.csv")
    r.add_argument("--models_dir",
                    default=r"C:\Users\acost\repos\transistor_modeling_hyper_outputs\archsearch_models",
                    help="Saved model weights + meta.json + metrics.json per combo. Defaults "
                         "OUTSIDE this repo (sibling folder) so runs never create untracked "
                         "files inside the git repo -- pass an absolute path to write anywhere "
                         "else. This is also the ONLY place resume state lives (filesystem-based "
                         "-- see combo_is_done): no results.csv is read or written by `run`.")
    r.add_argument("--n_f_architectures", type=int, default=None,
                    help="Limit to the first N rows of f_csv (e.g. 5 for a smoke test). "
                         "Default: use all rows in f_csv.")
    r.add_argument("--workers", type=int, required=True)
    r.add_argument("--batch_size", type=int, default=20,
                    help="f-architectures processed per ProcessPoolExecutor batch, before "
                         "moving to the next batch. Purely a parallelism-grain knob -- does NOT "
                         "affect resumability, since each combo's metrics.json is written "
                         "independently as soon as that combo finishes. Default 20 (-> "
                         "20*len(h_csv)*2 combos/batch).")
    r.add_argument("--epochs", type=int, default=1000,
                    help="Fast-proxy epoch count for LOO-fold ranking (no L-BFGS by default).")
    r.add_argument("--lr", type=float, default=3e-3)
    r.add_argument("--lbfgs_epochs", type=int, default=0)
    r.add_argument("--lbfgs_max_iter", type=int, default=200)
    r.add_argument("--gm1_weight", type=float, default=0.075,
                    help="Used by BOTH strategies.")
    r.add_argument("--gm_smoothing", choices=GM_SMOOTHING_METHODS, default="savgol",
                    help="Derivative estimator for the gm1 training target (see "
                         "signal_utils.gm_derivative / train_loo.py --gm_smoothing): 'savgol' "
                         "(default, base-repo port), 'cascade' (lighter, keeps gm2/gm3 peaks), "
                         "'none' (raw np.gradient). Folded into hp_hash EXCEPT at the default "
                         "'savgol', which hashes identically to pre-1760ca2 runs. Only affects "
                         "the training target -- the gm rel-RMSE metric stays on savgol.")
    r.add_argument("--weight_decay", type=float, default=0.0,
                    help="AdamW weight decay, used by BOTH strategies (H/H_comp AND the delta "
                         "strategy's theta_base fit). 0.0 (default) makes AdamW identical to "
                         "plain Adam -- fully backward compatible. Regularizes H's own weights "
                         "directly (aimed at the LOO generalization gap), not a fix for "
                         "optimization/local-minima issues.")
    r.add_argument("--delta_reg_weight", type=float, default=0.01,
                    help="'delta' strategy only: L2 penalty on delta_theta.")
    r.add_argument("--delta_base_epochs", type=int, default=1000,
                    help="'delta' strategy only: epochs to fit theta_base on BASE_KEY's data.")
    r.add_argument("--delta_base_lr", type=float, default=3e-3,
                    help="'delta' strategy only: learning rate for the theta_base fit.")
    r.add_argument("--delta_base_lbfgs_epochs", type=int, default=5,
                    help="'delta' strategy only: L-BFGS polishing steps for the theta_base fit.")
    r.add_argument("--seed", type=int, default=27)
    r.set_defaults(func=cmd_run)

    p = sub.add_parser("populate", help="Rebuild results.csv from --models_dir/*/metrics.json "
                                         "(no training, safe to run any time, repeatedly)")
    p.add_argument("--models_dir",
                    default=r"C:\Users\acost\repos\transistor_modeling_hyper_outputs\archsearch_models",
                    help="Scanned for <combo_id>/metrics.json under here. Should match whatever "
                         "--models_dir `run` was given (same location, or wherever it was "
                         "moved/copied to).")
    p.add_argument("--results_csv",
                    default=r"C:\Users\acost\repos\transistor_modeling_hyper_outputs\results.csv",
                    help="Rewritten from scratch each time this is run (one row per combo with "
                         "a complete metrics.json). Defaults OUTSIDE this repo (sibling folder).")
    p.add_argument("--with_gm", action="store_true",
                    help="Also score gm1/gm2/gm3 (and combined_gm = equal-weight mean) rel-RMSE "
                         "for each combo's FULL-FIT model, into the same results.csv. Reloads "
                         "every saved model and reads the measurement CSVs (needs --csv_dir); "
                         "per-combo results are cached in <combo_id>/gm_metrics.json.")
    p.add_argument("--with_loo_gm", action="store_true",
                    help="Fill the loo_gm* columns (held-out folds). The fold models weren't "
                         "saved, so this RETRAINS the folds of the top --loo_gm_top combos only "
                         "(by loo_mean_rel_rmse), caching in <combo_id>/loo_gm_metrics.json. "
                         "Needs --csv_dir. Combos trained after this feature already have loo_gm* "
                         "natively in metrics.json.")
    p.add_argument("--loo_gm_top", type=int, default=50,
                    help="--with_loo_gm: how many combos (best loo_mean_rel_rmse first) to "
                         "retrain folds for. Retraining all of them would ~= re-running the sweep.")
    p.add_argument("--csv_dir", default=r"C:\Users\acost\repos\csvs",
                    help="Measurement CSVs, used only by --with_gm / --with_loo_gm.")
    p.add_argument("--gm_workers", type=int, default=8,
                    help="--with_gm / --with_loo_gm parallelism (ProcessPoolExecutor). "
                         "1 = in-process, no pool.")
    p.add_argument("--gm_vds_step", type=float, default=GM_VDS_STEP,
                    help="Spacing (V) of the Vds levels the transfer curves (Ids vs Vgs at ~fixed "
                         "Vds) are built on: multiples of this strictly inside the measured sweep "
                         f"(default {GM_VDS_STEP} -> [3, 6, ..., 27] for 0-30 V data). Matches "
                         "build_gm_targets' default so the metric mirrors the training target.")
    p.add_argument("--recompute_gm", action="store_true",
                    help="Recompute every <combo_id>/gm_metrics.json and loo_gm_metrics.json "
                         "instead of reusing cached ones.")
    p.set_defaults(func=cmd_populate)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
